### ISSUE TITLE
Umbra Creation - Champion's Rest blocked

### ISSUE THREAD

**Issue by Jorst79** [Guitarninja2/septimus#10]
The entrance to the dungeon Champion's Rest added by the CC Umbra is blocked by added mountains from Mountains Enhanced. See attached pictures for examle and location. Used newest version of Anniversary profile (version 1.5.1)
![20211121172202_1](https://user-images.githubusercontent.com/94798187/142771309-cc9c4d0d-5418-48f5-818c-e69ace36f82c.jpg)
Example
![20211121172241_1](https://user-images.githubusercontent.com/94798187/142771332-48593095-58fb-4ec4-9196-eabc31324602.jpg)
Location

**Comment by Guitarninja2** [comment]
Ah yeah I'll likely just remove the mod that edits the mountains. Not entirely necessary. Came from base TPF.

**Comment by Guitarninja2** [comment]
Fixed in 1.6.0
