### ISSUE TITLE
Mod suggestion: All Geared Up Derivative (AllGud)

### ISSUE THREAD

**Issue by Neeksman** [Guitarninja2/septimus#100]
Although it might get too clumped up with wearing a backpack and having a scroll and whatnot on your back, it still boosts immersion! Besides you can pick and choose what you want to show!

https://www.nexusmods.com/skyrimspecialedition/mods/28833

**Comment by Guitarninja2** [comment]
This one I'm specifically leaving out due to the issues I've seen in elysium with it. Have seen many crashes. Also it's a bit of a pain to patch in custom armor heh.
