### ISSUE TITLE
Barrier perk from Alteration tree does not work.

### ISSUE THREAD

**Issue by adam-ciszewski** [Guitarninja2/septimus#101]
### Subject of the issue
The Barrier perk for the Alteration tree does not work correctly. The effect of dual cast flesh skill is not doubled.

### Your environment
Modlist version 1.10b
Custom mods outside of modlist:
- NightEyeENB fix
- Simply Faster Arrows and Bolts
- Know Your Enemy- Trait-based resistances and weaknesses.

### Steps to reproduce
- Dual-cast Ironflesh spell before acquiring the perk. With Balance (Rank I) it lasts for 3m 45s.
- Take the Barrier perk
- Dual-cast Ironflesh again

### Expected behaviour
Ironflesh should last for 8m 15sec or longer depending on the length bonus is applied.

### Actual behaviour
After taking the perk spell length is still only 3m 45s.

**Comment by adam-ciszewski** [comment]
This is now working on the official release of 1.10.

**Comment by adam-ciszewski** [comment]
After testing for longer, I'm still getting a short duration on the ironflesh/oakflesh spell.

**Comment by Guitarninja2** [comment]
This seems to be fixed in 2.0.0
