### ISSUE TITLE
Mod Suggestion: Refine Series of Character Overhauls

### ISSUE THREAD

**Issue by Atem777** [Guitarninja2/septimus#103]
They look great, and there's a patch for them when using AI Overhaul.

You can find them here. The patch requires all of them though.

https://www.nexusmods.com/skyrimspecialedition/users/47365508?tab=user+files

https://www.nexusmods.com/skyrimspecialedition/mods/58355

**Comment by Atem777** [comment]
For consistency with wood elves I would also suggest Bosmer Have Antlers.

https://www.nexusmods.com/skyrimspecialedition/mods/33349

And to give NPCs unique heights I would suggest Diverse Heights.

https://www.nexusmods.com/skyrimspecialedition/mods/52057

**Comment by Atem777** [comment]
Then finally there's Trag's overhauls BUT they need a patch for AI Overhaul. I found Captivating Companions and Elegant Elves worked great with Refine when Elves overwrites it. The former doesn't overwrite Refine since it doesn't change the companions. Dashing Dawnguard looks good too but touches Serana's looks.

https://www.nexusmods.com/skyrimspecialedition/users/7230534?tab=user+files

**Comment by Guitarninja2** [comment]
At the moment I'm going to leave out npc overhauls but I may come back to this.
