### ISSUE TITLE
Unable to Complete Download

### ISSUE THREAD

**Issue by walshcon000** [Guitarninja2/septimus#104]
Got to the very end of the Wabbajack install and then
[Wabbajack.current.log](https://github.com/Guitarninja2/septimus/files/7716136/Wabbajack.current.log)
 it threw this error. Any help would be greatly appreciated!

**Comment by Guitarninja2** [comment]
Oh yeah that file was giving me problems for some reason. Grab the newest one from the gallery. It should be fixed now.

**Comment by Guitarninja2** [comment]
1.10.0.1 is the fixed version
