### ISSUE TITLE
A Few Mod Suggestions

### ISSUE THREAD

**Issue by Foamimi** [Guitarninja2/septimus#105]
Hello! There are a few mods I've stumbled across over the past few years that cover retextures, mesh edits, addons, etc. for some of the quest mods I noticed were included in the loadorder. I thought I'd mention them just in case they piqued interest. If not no worries of course! It never hurts to at least try. <3

For the Forgotten City: 
[No Audio Books](https://www.nexusmods.com/skyrim/mods/83593)

For Beyond Skyrim - Bruma:  
[CC's HQ Roadsigns](https://www.nexusmods.com/skyrimspecialedition/mods/2778) (just the Bruma files)
[Beyond Skyrim - Bruma - Boobless Iron Armor](https://www.nexusmods.com/skyrim/mods/88560)

For Helgen Reborn:
[CC's HQ Guard Shields](https://www.nexusmods.com/skyrimspecialedition/mods/1129) (just the Helgen files)

For Moon and Star: 
[Better Lighting for Moon and Star - with Lanterns of Skyrim II Patch](https://www.nexusmods.com/skyrimspecialedition/mods/43702) (+the DLC integration patch in the Optional section)
[Moon and Star - Creation Club Indoril Ordinator Armor Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/43688)
[Greenboat Moon and Star](https://www.nexusmods.com/skyrimspecialedition/mods/20051) (ESPFE version in Optional section)

**Comment by Guitarninja2** [comment]
I have added several of these. Thank you for the suggestions!
