### ISSUE TITLE
Bugged mountainpart at entrance of Oio-Lalor

### ISSUE THREAD

**Issue by Jorst79** [Guitarninja2/septimus#11]
Near the entrance of Oio-Lalor, a location added by Tools of Kagrenac, is a bugged mountainpart. See attached pictures for example and location. Used newest version of Anniversary profile (version 1.5.1)
![20211121172445_1](https://user-images.githubusercontent.com/94798187/142771543-40c21b57-7e40-4f9d-a245-3f9780c73f04.jpg)
Example
![20211121172536_1](https://user-images.githubusercontent.com/94798187/142771552-02841e48-c2d7-4231-b17f-6969109ecf33.jpg)
Location

**Comment by Guitarninja2** [comment]
Fixed in 1.6.0
