### ISSUE TITLE
Terrain Issues @ Myrwatch

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#113]
![enb2021_12_16_10_42_42](https://user-images.githubusercontent.com/95932072/146401618-3fdc71ab-923d-451c-8363-05ac8ba16ee2.png)
![enb2021_12_16_10_42_49](https://user-images.githubusercontent.com/95932072/146401619-a41138d5-778c-4363-a4f8-ac398aba5a36.png)

**Comment by Guitarninja2** [comment]
Sorted this one out for 1.10.1
