### ISSUE TITLE
Mod Suggestions

### ISSUE THREAD

**Issue by ARSOD-Z** [Guitarninja2/septimus#117]
Time Flies: Time passes when crafting, reading, eating, trading, looting, lockpicking, building campfires, homes, etc. Time Flies is a modified version of Living Takes TIme w/mod support for Hearthfire, Hearthfire Extended, Campfire, Basic Camp Gear, iNeed, SunHelm, Last Seed, Skyrim Fishing, & Hunting in Skyrim. Compatible w/CACO, Honed Metal, Hunterborn.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/39426

Dynamic Timescale: Changes your game's timescale based on whether you are outdoors, indoors or in combat. Can perform periodic AutoSaves. This is a port to SSE of Kae Arby's Dynamic Timescale. Requires Dawnguard and Dragonborn DLC.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/18922

Immersive Interactions: See your character perform context-aware animations when interacting with the world. Animated greeting of NPCs, pickpocketing, lockpicking, and more!
Link: https://www.nexusmods.com/skyrimspecialedition/mods/47670

I'm Glad You're Here: Allows the player to show their appreciation to their followers , spouse and adopted kids by dialogue and a hug animation. Fully voiced dialogue.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/41856

Sidequests of Skyrim: Perform radiant side quests for almost any NPC. Get rewarded and become friends with NPCs
Link: https://www.nexusmods.com/skyrimspecialedition/mods/54245

Security Overhaul - Some More Locks: Adds some more individual locks to the game.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/59961

Hearthfire Extended: The essential expansion for Hearthfire. New content for the Hearthfire DLC, integrated seamlessly with Hearthfire's construction system. Build any furniture in any room. Build additional wings off your cellar. Also includes bugfixes and enhancements to vanilla apiaries, butter churns and mead barrels. Now with servants.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/8450

Immersive Spell Learning - DESTIFIED: A very simple and compatible version of Immersive Spell Tomes, using Don't Eat Spell Tomes, with added features from another bunch of similar mods. Survival Mode and SunHelm compatible.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/45514

Trailblazers: In the spirit of Requiem, no longer will the world feel like it solely resolves around the player. New NPCs — powerful or feeble, ally or foe, generic or unique — will wander, adventure and pillage throughout the lands of Skyrim.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/49112

Sky Idles SE: Sky Idles is an condition based 3rd person idle animation collection for Skyrim SE.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/45794

Armoury of Tamriel 2.0: Armoury of Tamriel is a weapons and armour overhaul that sets out to separate material from design. Every weapon and armour, craft-able and found in the world as loot and on NPCs, in iron, steel, moonstone, orichalcum, silver, dwarven, glass, ebony, and daedric. That's 1,158 new weapons, and 1,863 new armours! 3,021 new pieces of gear to play with!
Link: https://www.nexusmods.com/skyrimspecialedition/mods/29346

Relationship Dialogue Overhaul: Adds over 5,000 lines of completely voiced dialogue for NPCs using the original voices. Friends, followers, spouses, rivals, and others have much more to say. All default voices now have follower dialogue. Also fixes dialogue bugs and restores cut dialogue that has never been heard before!
Link: https://www.nexusmods.com/skyrimspecialedition/mods/1187

Reading is Good: This mod reworks skill books so that instead of granting levels instantly, they give you a permanent boost to your leveling speed in the respective skill. This means that you benefit more by reading them as soon as you find them.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/42026

Skyrim Reputation: Skyrim Reputation introduces a reputation mechanic to make you treated as the hero or villain you really are, without it interfering with your game-play. All functions of the mod can be toggled on/off in the MCM menu.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/52416

More Immersive NPCs: A mod that adds many new NPC's that wander organically throughout Skyrim using custom AI packages, in an attempt to make traveling more dangerous, and the roads less empty.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/29483

Missives - Worldspace Additions: This is a compilation of patches for Missives and several new landspace mods.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/26788

Headhunter - Bounties Redone: Bounty quests expanded for Bandits, Forsworn, Giants and Dragons. Like in the Witcher 3, bring "trophies" from your enemy to the Jarl as proof of the bounty or deliver the captured bandits to a guard for justice. Support for Missives, The Notice Board, AllGUD and more.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/51847

BA Bard Songs: This mod adds bard drum, flute, and lute instrumental songs to the taverns. It does not REPLACE them, it ADDS them and they play at RANDOM!
Link: https://www.nexusmods.com/skyrimspecialedition/mods/47202

The Notice Board: This mod adds new and alternative radiant (and side) quests. It was inspired from other good games like The Witcher which make use of notice boards in their gameplay. 
Link: https://www.nexusmods.com/skyrimspecialedition/mods/3218

Follower Commentary Overhaul: A mod which injects new life into the vanilla followers of Skyrim by greatly expanding their repertoire of idle, conditional commentary using only vanilla resources.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/16865

Immersive Speechcraft: Adds several dialogue options to most of Skyrim's NPCs (even ones initially without any dialogue options) allowing for increased immersive interactions and role-play. Compatible with every dialogue overhaul / commentary mod such as FCO SE, RDO, GDO and others as it does not conflict or replace and only adds more dialogue.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/21296

Daedric Voices: Adds dialogue from the Daedric Princes when using their artifacts.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/32090

Talkative Dragons: Ever found it weird that dragons, fully sapient beings, have never spoken a word while you’re doing your best trying to defeat them? This mod changes that.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/26955

Faction Warfare: Adds dynamic warfare to Skyrim. Factions wage war with one another, and you can choose to lead one or more Factions. Lead a Faction to summon its troops. Equip almost any NPC through the Faction Armories.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/32997

Spell Research: Adds a completely new system to research and discover spells from any supported spell mod. As well as adding an in-built spell tome and scroll crafting system, a Victorian-Era style alchemy system, where you can dissolve items, and mix or analyze the resultant solutions, and expands the lore of magic with dozens of texts and artifacts to find.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/20983

Holidays: Villages/cities will visually change as holidays based on TES lore come and go. NPCs will also react to these changes by attending various events appropriate for the holiday.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/1533

Death Alternative - Your Money or Your Life: This mod is a framework to handle defeat narratives. When you are defeated, one of many random events may occur depending on the context. You may be left for dead, transported to a shrine, have your items stolen, etc. Follower are supported and play an active role in the gameplay dynamics.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/13264

Real Names: Real Names automatically assigns a lore-friendly name to anonymous NPCs.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/17827

Hunterborn: Changes animal looting into a process of dressing, skinning, harvesting, and butchering. Adds hunting knives, many new alchemy ingredients, animal meat, recipes, and foraging.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/7900

Thunderchild: Thunderchild enables players to create shout-centric characters, adding 29 new shouts with multiple effects. It also includes several buffs that are unlocked by completing Kyne's tests of faith, a custom Greybeard Robe in several variations, the High Hrothgar Library, and an assortment of buffs and bugfixes for vanilla shouts.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/1460

Apocalypse: Apocalypse is the most popular Skyrim spell pack, adding 155 new spells that are unique, balanced, lore friendly, use high quality custom visuals and blend seamlessly into the vanilla magic system. Also includes scrolls and staves for the new spells.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/1090

Enemy (R)evolution of Skyrim: Enemies will use Spells/Perks/Items/Shouts which were previously limited to the player only. Adds support for dozens of Mods. Lore-friendly implementation, highly customizable. No Scripts and no Plugin ;)
Link: https://www.nexusmods.com/skyrimspecialedition/mods/37228

Maximum Carnage: Maximum Carnage is a gore mod made for those who want a more bloody and gory Skyrim. Chop off limbs, burn your opponents to a crisp, its your choice. This mod was inspired by lamer1000's amazing Deadly Mutilation mod, so a big shout out and thanks to him\her.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/43494

Summermyst: Summermyst adds 120 new enchantments to the game. The new enchantments are integrated seamlessly into the vanilla item system. It also makes many improvements to vanilla enchantments.
Link: https://www.nexusmods.com/skyrimspecialedition/mods/6285

Royal Armoury: Adds special weapons to the most important characters in Skyrim. Ulfric Stormcloak and General Tullius now carry weapons to fit their station!
Link: https://www.nexusmods.com/skyrimspecialedition/mods/6994

**Comment by Guitarninja2** [comment]
Some of these have been added. Most not.
