### ISSUE TITLE
Texture Glitch

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#118]
![grafik](https://user-images.githubusercontent.com/95932072/146615812-ee968584-511d-492a-9f06-2aeeee323afc.png)
![enb2021_12_17_23_36_35](https://user-images.githubusercontent.com/95932072/146615822-1ecfa0c3-1d5f-41c8-a8e3-f3763611b692.png)

**Comment by Guitarninja2** [comment]
cringe
