### ISSUE TITLE
Flying tree near Oio-Lalor

### ISSUE THREAD

**Issue by Jorst79** [Guitarninja2/septimus#12]
Near the entrance of Oio-Lalor, a location added by Tools of Kagrenac, is a flying tree. See attached pictures for example and location. Used newest version of Anniversary profile (version 1.5.1)
![20211121172658_1](https://user-images.githubusercontent.com/94798187/142771620-56860baf-e899-497e-99c7-9e72957000a9.jpg)
Example
![20211121172719_1](https://user-images.githubusercontent.com/94798187/142771629-c0e44a46-e15a-434b-b10e-74da8647d5b2.jpg)
Location

**Comment by Guitarninja2** [comment]
Thank you! Should be an easy fix.

**Comment by Jorst79** [comment]
No problem. Thank you for the modlist!

**Comment by Guitarninja2** [comment]
Fixed in 1.6.0
