### ISSUE TITLE
Crash outside of Falkreath

### ISSUE THREAD

**Issue by Gattsun** [Guitarninja2/septimus#122]
I seem to crash at one specific place right outside of Falkreath, if I walk past the carriage down the road then my game crashes. If I walk around that area then my game works fine
[Crash_2021_12_18_23-25-49.txt](https://github.com/Guitarninja2/septimus/files/7739999/Crash_2021_12_18_23-25-49.txt)
![20211218232956_1](https://user-images.githubusercontent.com/70638401/146656147-0813c81d-a46d-432e-a732-9a75a7bcbd1e.jpg)

**Comment by Guitarninja2** [comment]
Yeah I'm seeing this one too. Investigating. Very strange one.

**Comment by Guitarninja2** [comment]
Aha! It was the recent beyond skyrim bruma update with broken files causing another mod to crash. Madness. Will be fixed in the next update.
