### ISSUE TITLE
Iron Plate Helmet allows hood to be worn.

### ISSUE THREAD

**Issue by Tarzier** [Guitarninja2/septimus#124]
You can wear the Iron Plate Helmet with hoods. Potentially the other plate helmets as well, though I didn't test that
![enb2021_12_19_01_44_03](https://user-images.githubusercontent.com/79779990/146667294-1995c47c-cf2f-4c3a-83ce-b8c02c78e6cb.png)
![enb2021_12_19_01_44_06](https://user-images.githubusercontent.com/79779990/146667302-1331cfa6-fee1-4269-8901-47baf38cfcc3.png)
.

**Comment by Calcyon85** [comment]
Still an issue, tried the Ebony and Orcish Plate helmets as well but they didn't have the issue

**Comment by Webmetz** [comment]
The Iron Plate Helmet has the slots
30 - Head, 42 Circlet

Many Hoods take up the slots
31 - Hair, 42 Ciclet
or
31 - Hair, 41-Long Hair, 42 Circlet

However, some simply take up the slot
31 - Hair
allowing you to wear a circlet with it.

This explains why this is happening.  The question is... 
Do we want to disable Circlets for all Hoods?

Some Helmets just Take Up the Slots
31 - Hair
or 
31 - Hair, 42 Circlet
or 
30 - Head, 31 Hair, 42 Circlet

Do we want to convert all Helmets
30 - Head, 42- Circlet
to 
30 - Head, 31 Hair, 42 Circlet
