### ISSUE TITLE
Floating trees 

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#125]
![grafik](https://user-images.githubusercontent.com/95932072/146673613-bf465682-f5ec-45a7-9e4d-a18975583225.png)
![grafik](https://user-images.githubusercontent.com/95932072/146673625-86394c98-82fe-4d4e-b797-ab6ec78213e7.png)
![grafik](https://user-images.githubusercontent.com/95932072/146673631-a8ac9c68-a036-4aa6-93e0-3233ced6a61d.png)

**Comment by Guitarninja2** [comment]
My immersion is ruined

**Comment by Calcyon85** [comment]
Ran around the entire area and couldn't find the floating trees

**Comment by Guitarninja2** [comment]
Likely fixed now then.
