### ISSUE TITLE
Bug: Pets of Skyrim conflict in Rorikstead

### ISSUE THREAD

**Issue by natelovesyou** [Guitarninja2/septimus#127]
There's a ramp that goes over Halvar's bedroll and the guide book from Pets of Skyrim.

![SkyrimSE_88MgTmBGMj](https://user-images.githubusercontent.com/16608135/146694726-65052f98-bba8-400c-9177-6af9b6b8634d.jpg)

**Comment by Guitarninja2** [comment]
This should be fixed in 2.0
