### ISSUE TITLE
Mod Suggestion: More Player Home Options SE

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#128]
https://www.nexusmods.com/skyrimspecialedition/mods/36714

Utilizes homes abandoned in the process of vanilla quests. Allowing you to buy them from stewards.

DESCRIPTION

A Skyrim SE port of More Player Home Options. Adds the option for the player to acquire certain vanilla NPC homes that become vacant during/after certain quests are either completed or after certain decisions are made.

As you play through Skyrim, you'll notice that quite a few quest actually have you kill a named NPC, or a named NPC dies from a scripted event. This isn't anything surprising or interesting in Skyrim, as most of the problems the Dragonborn faces are solved by killing something. However, some of these named NPCs have houses, that will now be vacant for the rest of your play-through. This mod allows the player to purchase/acquire some of these houses.

This mod started of as Tweakx's personal creation to allow his characters to purchase houses in some of the cities that didn't have them in the base game (Morthal, Dawnstar), but later decided to expand it to more houses. This was to enable different characters to get different houses each play-through.

Below are the houses currently covered and how they can be acquired, i.e. [HOME] > [REQUIREMENTS].
(Note: Once the requirements are met, the player may have to switch locations for the quests to start)

- Ironstad Cabin (Beitild's House) - Thane of Dawnstar and have completed the Dark Brotherhood side contract to kill Beitild.
- Vesuius Homestead (Silus Vesuius Museum) - Thane of Dawnstar and have opted to kill Silus in the "Pieces of the past" quest.
- Marshloom (Alva's House) - Thane of Morthal and have completed the "Laid to Rest" quest (Saving Hroggar may cause him to stay in the house with the player character)
- Mysterious House (Abandoned House) - Complete the "House of Horrors" quest.
- House of Curiosities (Calixto's House of Curiosities ) - Complete the "Blood on the Ice" quest (Find the real killer).
- Reachman's Rest (Nepos' House) - Kill Nepos and his servants during or after "Forsworn Conspiracy" Quest, and help Thonar by killing Madanach during "No One Escapes Cidna Mine" Quest. [Speak with Thonar Silver-blood at his home to purchase the house]
- Riftweald Manor (Mercer Frey's House) - Complete the Thieves guild main quest mission "Blindsighted" then speak with Maven Black-briar to purchase the house. [Alternatively, you can instead become the leader of the Thieves guild to get the house from Maven for free.]
- Mixwater Cabin (Mixwater Mill's Worker's House) - Explore the house's interior then speak to Gilfre at the lumber mill.
- Secluded Hut (Lund's Hut) - Explore the house's interior then speak to Rorik in Rorikstead.
- Half-Moon Mill - Must become a thane of Falkreath and have completed the Dark Brotherhood side contract to kill Hern. Hert must also have been killed. Speak to the Steward.
- Thornwood Shack (Abandoned Shack) - Speak to Benor in Morthal after either killing Astrid and completing the "Destroy the Darkbrotherhood" quest or finishing the Darkbrotherhood questline.
- Scout's Lodge (Abandoned Lodge) - Complete the side quest "A New source of Stalhrim" then speak to Fanari Strong-Voice.

When conditions are met, you can talk to either the Jarl or Stewards for the respective city and buy the house(s).

**Comment by Guitarninja2** [comment]
This is in.
