### ISSUE TITLE
Brotherhood of Old / Bittercup CC incompatibility

### ISSUE THREAD

**Issue by Captain-Staky** [Guitarninja2/septimus#129]
There's a door in the Warrens in Markarth that is added by Bittercup that is opened with Key to Eslaf's Room

There's also a quest objective from Brotherhood of Old that is behind the door and can't be reached without doing CC content first.

**Comment by Captain-Staky** [comment]
The only way to enter the room is being forced into a specific path in the Bittercup questline

**Comment by Captain-Staky** [comment]
Back entrance that could be used instead
![2021-12-20 11_02_47-Greenshot](https://user-images.githubusercontent.com/44516691/146804835-fb62d662-eb81-42f6-b938-e2de8c5c8f2e.png)

**Comment by Guitarninja2** [comment]
Brotherhood of old yeeted out
