### ISSUE TITLE
Langleys hut (INIGO) blocked by mountains added by Mountains Enhanced

### ISSUE THREAD

**Issue by Jorst79** [Guitarninja2/septimus#13]
The mod Inigo adds near Snow Point Beacon the hut of Langley, which you get sent to later in Inigo's quest. The hut and the path to Langleys hut are currently blocked by mountainparts added by Mountains Enhanced. Best way to find this is by fast travelling to Snow Point Beacon and walking through the tower to the spot of Langleys hut. Added pictures of the rough location.

![20211121172945_1](https://user-images.githubusercontent.com/94798187/142771839-b0c66ffd-6755-4e03-a7a9-f42d75129f6e.jpg)

![20211121173422_1](https://user-images.githubusercontent.com/94798187/142771841-8ad33a6a-075d-4e97-b636-fccfc2bcd626.jpg)

**Comment by Guitarninja2** [comment]
This should be fixed in 1.6.0
