### ISSUE TITLE
Immersion ruined, immeasurable disappointment >:(

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#130]
![grafik](https://user-images.githubusercontent.com/95932072/146828814-7b2d4637-3ea5-4086-8632-78d96b31ea62.png)
![grafik](https://user-images.githubusercontent.com/95932072/146828847-de114617-4435-47b6-b717-f5bee1527073.png)
![grafik](https://user-images.githubusercontent.com/95932072/146828871-c2207d1f-1834-44b7-badb-345dadfc17e4.png)

**Comment by Guitarninja2** [comment]
This is fixed now in 2.0 :D
