### ISSUE TITLE
Dragontooth crater word wall

### ISSUE THREAD

**Issue by SpaghettiExcuse** [Guitarninja2/septimus#132]
Can't read the word of power from the wall.
![image](https://user-images.githubusercontent.com/96251729/146853720-3783312a-43be-43ea-81bc-9977fce201cb.png)

Also the dragon language words sort of overlap? weird. You can even console and click on the real words. I don't know

**Comment by Calcyon85** [comment]
Can't learn Word of Power or even read the wall either when I tried

**Comment by Guitarninja2** [comment]
Fixed in 2.0.0-beta5
