### ISSUE TITLE
Helgen Reborn (Bitter wounds) quest

### ISSUE THREAD

**Issue by SpaghettiExcuse** [Guitarninja2/septimus#133]
![image](https://user-images.githubusercontent.com/96251729/146994715-f4b48997-aa49-4373-a73c-447420b6d75b.png)

Quest in the Helgen Reborn mod can't complete, says there is 1 left. 
Reported by me and "You Banana"
I tried /killall but nothing worked

**Comment by Calcyon85** [comment]
Helgen Reborn is no longer in Septimus

**Comment by Guitarninja2** [comment]
Closing this one out as "fixed" in 2.0
