### ISSUE TITLE
Mod Wonderings - Snazzy Item Series for Custom Followers + Kaidan 2

### ISSUE THREAD

**Issue by Foamimi** [Guitarninja2/septimus#135]
Hello again! I forgot to mention in my past suggestion these retextures for some of the custom follower mods included in the guide. All they do is add HD meshes and textures to some of the gear and tools utilized by the various followers.

[Snazzy Items for Inigo](https://www.nexusmods.com/skyrimspecialedition/mods/57194)
[Snazzy Items for Auri](https://www.nexusmods.com/skyrimspecialedition/mods/57195)
[Snazzy Items for Interesting NPCs (3DNPC)](https://www.nexusmods.com/skyrimspecialedition/mods/58811)

Then for Lucien, there's always [Pandorable's Lucien Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/22598) if you're in search of any visual upgrades to his character.

On another note, if you ever decide to add [Kaidan 2](https://www.nexusmods.com/skyrimspecialedition/mods/19075) to the guide, he has a few visual upgrades as well. I just thought I'd add these on the off-chance he was being considered since I hadn't seen any comments referring to him yet.

[Pandorable's Kaidan Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/23738)
[Kaidan 2 Katana Replacer](https://www.nexusmods.com/skyrimspecialedition/mods/44905)
[Kaidan 2 - HD Armor Retexture](https://www.nexusmods.com/skyrimspecialedition/mods/59736) (by me!)
[Kaidan 2 Follow Distance Fix](https://www.nexusmods.com/skyrimspecialedition/mods/49433) (Optional file)
[Kaidan 2 Follower Voice Fixes and Additional Dialogue and Dawnguard DLC](https://www.nexusmods.com/skyrimspecialedition/mods/59349)
[Inigo Marriage Commentary Patch for Kaidan 2](https://www.nexusmods.com/skyrimspecialedition/mods/36023)

Sorry for all the links! This should be all I wanted to suggest, so there shouldn't be another post by me for a while. I hope one, if any, of these catch your drift! Either way, thanks so much for the guide. <3

**Comment by Guitarninja2** [comment]
Kaiden 2 is in. I will probably grab the inigo patch too when I have time to check it. Thanks for the suggestions :)
