### ISSUE TITLE
[2.0] Sexier Vanilla Guards removes the cloaks from "Winter is Coming"

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#142]
![unknown](https://user-images.githubusercontent.com/2394842/147317896-a28f9a34-1d05-41df-9c24-7c75e90b3f46.png)
OutfitListGuardWinterhold

Sexier Vanilla Guards removes the cloaks from "Winter is Coming"

**Comment by Guitarninja2** [comment]
Fixed
