### ISSUE TITLE
[2.0] LootDraugr1HWeapon100 needs merging or OWL Patch

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#143]
It looks like Private Armory is removing some Animated Armory stuff in LootDraugr1HWeapon100.    I am surprised OWL didn't catch this
![unknown](https://user-images.githubusercontent.com/2394842/147317973-4801c292-cc4b-4def-983f-4e7ef0d8f287.png)
.

**Comment by Guitarninja2** [comment]
Fixed
