### ISSUE TITLE
[2.0] OWL doesn't include Common Armors stuff

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#147]
[2.0] OWL doesn't include Common Armors stuff

Example: Looking at the OWL_Armor_Fur_Cuirass list, it doesn't include the additional armors from Common Clothes and Armors.
![unknown](https://user-images.githubusercontent.com/2394842/147318342-a66ee1f8-ae2d-4b44-89ac-79395611d7c6.png)

**Comment by Guitarninja2** [comment]
This is good now
