### ISSUE TITLE
[2.0] Forgotten City Removes Bruma Head Parts

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#148]
Forgotten City removes some Head Parts for Bruma.
HeadPartsHumansandVampires [FLST:000A8023]
![unknown](https://user-images.githubusercontent.com/2394842/147318411-b1c763fd-e6f7-4213-b7e0-79a26557c23f.png)

**Comment by Guitarninja2** [comment]
Fixed
