### ISSUE TITLE
Interior Floating Fog Remover mod not working (fog/dust in caves)

### ISSUE THREAD

**Issue by natelovesyou** [Guitarninja2/septimus#15]
I'm unsure if this is also an issue in base TPF, but it is for me in Septimus. In all caves so far, there's still fog despite the presence of Interior Floating Fog Remover (mod filename: No Floating Fog-4298-1-1): https://www.nexusmods.com/skyrimspecialedition/mods/4298
![image](https://user-images.githubusercontent.com/16608135/142805083-4643a9f8-f94b-44fd-aace-21b51c720628.png)

**Comment by Guitarninja2** [comment]
Looks like that mod only removed one specific type of fog. The kind you're seeing is supposed to be there.
