### ISSUE TITLE
[2.0] Immersive NPC Skjarn missing his face

### ISSUE THREAD

**Issue by 4ulender** [Guitarninja2/septimus#152]
![20211224184602_1](https://user-images.githubusercontent.com/96638017/147374439-ff990d59-9090-482b-a578-3ff41e139eac.jpg)

Using Septimus 2.0 Beta 2 with Medium INIs and the optional Random Start mod. Entered the tavern in Dragon Bridge and found this NPC with a missing head/face. Skjarn is from Immersive NPCs.

**Comment by Guitarninja2** [comment]
Thanks lol. I noticed a couple of these. Will check this out next on my list.

**Comment by Guitarninja2** [comment]
Fixed in 2.0.0-beta 5
