### ISSUE TITLE
Mod Suggestions / Missing Mods from 1.0

### ISSUE THREAD

**Issue by Durgenage** [Guitarninja2/septimus#153]
This is a list of mods that were present in Septimus 1.0 that are NOT present in version 2.0
This is NOT all of the missing mods. It only includes mods that I would like to see continue into Septimus 2.0+
I have emphasized the mods that I personally feel are the most important in **bold**
I have not included links because there are too many mods. For the most part you can double click to highlight, and then search with google
I realize that there may be reasons that these were left out, but am posting this on the off chance that they were just forgotten
On to the list:

TWEAKS

Dwemer Gates Don't Reset
Calcelmo Has Standards
Windhelm Segregation
Alik'r Warriors Aren't Welcome
Assorted Tiny Tweaks
Realistic Conversations
Simply Smaller Wolves
**No Crime Teleport**

INTERFACE

**Favorite Things - Extended Favorites Menu**
Shouts in the Dragon Tongue
Simple Load Screens
**Atlas Map Markers**
Weather of World

CONTENT

**Paraglider**

GAMEPLAY

**Simple Werewolf Favorite Howls Menu**
**Forceful Tongue - SimonRim Patch**
**Dragon Aspect Overhaul**
**Scion - Vampiric Sunscreen Plugin**
Mysticism Spells for NPCs
**Apothecary Patches**

LOOT AND CRAFTING

Armor and Clothing Extension
Tweaks for WACCF and ACE
Ancient Nord Stahlrim
**Bounties Are Worthwhile - Leveled Bounty Rewards**
**Simple Smithing Overhaul**
**Lightweight Smithing Tweaks for SSO**
Craftable Torches
**Fearsome Fists - Thaumaturgy Consistency Patch**

NPCs

AI Overhaul
**Simple Offence Suppresion**
Guard Dialogue Overhaul
Misc Dialogue Edits
More Dialogue Options - for Misc Dialogue Edits
Hunters Dialogue Edit
Hunters Not Bandits
Thugs Not Assassins
Thugs Not Assassins - Timing is Everything Patch
Adopt Aventus Aretino

IMPROVED VANILLA QUESTS

**Radiant Requirements MCM**
A Lovely Letter - Alternate Routes
Finding Derkeethus
Finding Susanna Alive
**Improved Companions - Questline Tweaks**
**The Companions - Don't Be a Milk Drinker**
**More Radiant Quests for the Companions**
**Companions Werewolf Bloodritual Scene Tweak**
Misc College of Winterhold Tweaks
Choose Your Own Arch-Mage
Finding Vehlek Sain
Sable's Bits and Bobs - The Last Dragonborn Perk
Andrealphus' Tweaks - Harder Mara Quests
Andrealphus' Tweaks - No Easy Bloodkin
**Reasonable Quest Rewards**
Reasonable Quest Rewards - Dark Brotherhood
Reasonable Quest Rewards - Bounties Are Worthwhile Patch
Boethiah for Good Guys
Adoption Without Murder (Innocence Lost for Good Guys)
Chill Out Aela

COMBAT AND ENCOUNTERS

**Mortal Enemies**
Disarming Traps is Dangerous
No Road Predators Redone
No Road Predators Redone - Less Predators Addon
Sable's Bits and Bobs - Steam Driven Automatons

MISCELLANEOUS

Misc Tweaks - Better Ancient Knowledge Perk
Ish's Respec Mod
**Bounty Preview**
Sleeves for Guards
Dragon Wall Wisdom - Readable Dragon Walls
Forceful Tongue - Dragon Wall Wisdom Patch
Unique Dragon Aspect
Durnehviir Resurrected
Forceful Tongue - Durnehviir Resurrected Patch
**Contraband Confiscation**
Delphine's Map Reveals Dragon Mounds
Bring Meeko to Lod
Karstaag - The Frost King Reborn
**Forget Spell**
Simply Knock SE
Just Blood - Dirt and Blood Lite
Dirt and Blood HD Retexture
First Person Camera Height Fix
Dismiss Steward
Vanilla Script (micro)Optimizations
Hide Your Quests
**Khajiits Steal Too - Caravan Fence Option**

SKSE Plugins

**Classic Paralysis**
**Enhanced Reanimations**
**Essential Favorites**
Vampires Cast No Shadow
**Uninterrupted Invisibility**
**Uninterrupted Ethereal Form**

OPTIONALS

**Complete Widescreen Fix**

**Comment by Guitarninja2** [comment]
Hey thank you for going through these. I had not done a full inventory of what was from TPF and what wasn't. I will likely enb up re-adding almost every one of these for the full 2.0 release. Thanks again.
