### ISSUE TITLE
[2.0] Dynamic Things Alternative issue

### ISSUE THREAD

**Issue by Calcyon85** [Guitarninja2/septimus#154]
The training dummy leveling isn't working on any training or archery dummy I've tried. I checked multiple areas just incase.

**Comment by Durgenage** [comment]
[https://www.nexusmods.com/skyrimspecialedition/mods/22854](https://www.nexusmods.com/skyrimspecialedition/mods/22854)
Version 4.5.5 of powerofthree's Papyrus Extender broke that functionality. Downgrading to Version 4.5.2 fixes it.

**Comment by Guitarninja2** [comment]
This should be fixed in the new version
