### ISSUE TITLE
Bandoliers Price/Weight overwritten by patch

### ISSUE THREAD

**Issue by Durgenage** [Guitarninja2/septimus#157]
Leather Box Pouch - Back Left and Dark Box Pouch - Back Left need to have their weight and values fixed to be in line with the rest as set by BandolierForNPC.
![bandolier](https://user-images.githubusercontent.com/96037567/147403703-cde35518-9903-4e3c-b48a-f6e491f39bda.png)

**Comment by Guitarninja2** [comment]
This should be fixed in beta 6
