### ISSUE TITLE
[2.0 Beta 7] Missing Masters in Anniversary Profile

### ISSUE THREAD

**Issue by montydudani** [Guitarninja2/septimus#158]
Anniversary Profile is missing master with WACCF gone
![missing masters](https://user-images.githubusercontent.com/96743083/147495545-4f8a683c-1645-4e29-841c-19a47d2148e5.PNG)

**Comment by Guitarninja2** [comment]
Oh yeah I re-uploaded this. Should be fixed now with the new BETA 7. My bad.
