### ISSUE TITLE
Unable to download Data_Dawnguard.esm

### ISSUE THREAD

**Issue by MrayaJanar** [Guitarninja2/septimus#159]
The files are in the downloads folder; but, for some reason the install always fails at this point.  I've looked over the walkthrough but nothing quite covers ..this particular issue, and I suspect it pertains to the Stock Skyrim that comes with it?  Help?

**Comment by Guitarninja2** [comment]
Can you post your wabbajack install log?

**Comment by MrayaJanar** [comment]
[Wabbajack.current.log](https://github.com/Guitarninja2/septimus/files/7781956/Wabbajack.current.log)

**Comment by Guitarninja2** [comment]
Verify your files in steam and make sure your game is up to date.

**Comment by MrayaJanar** [comment]
Done and done and problem persists.

**Comment by Guitarninja2** [comment]
Come by the discord and we can help you out.

**Comment by Guitarninja2** [comment]
It is linked in the install guide

**Comment by MrayaJanar** [comment]
I'm a dork.  It was the simple thing.  Problem solved.

**Comment by Guitarninja2** [comment]
No worries lol. Enjoy!
