### ISSUE TITLE
Add a mod that prevents follower friendly fire

### ISSUE THREAD

**Issue by natelovesyou** [Guitarninja2/septimus#16]
Guitarninja - you mentioned [here on Discord](https://discord.com/channels/458216677792808961/814215308158959616/912595922448437308) that you'd like to add a mod that prevents follower friendly fire.

This was after I mentioned that my two followers keep getting into fights after Uthgerd's sweeping attacks would hit the other.

(Also, I am pretty certain their attacks are hurting me as well, so I personally would like to not be hurt by my own followers as well...)

**Comment by Guitarninja2** [comment]
This will be good in 1.6.2
