### ISSUE TITLE
Carlotta Valencia in Whiterun defaults to rank 4 disposition

### ISSUE THREAD

**Issue by Durgenage** [Guitarninja2/septimus#162]
I believe it is caused by Interesting NPCs. I found something on google, and then I tested with 3DNPCs and all it's dependencies disabled and it was fixed. I'm not good enough with xedit to find out why. Good luck!

**Comment by Guitarninja2** [comment]
That is actually super useful info. Thank you.

**Comment by Guitarninja2** [comment]
This is due to a relationship records in interesting npcs. Should be able to remove it or change the relationship rank in it.

**Comment by Guitarninja2** [comment]
Fixed in 2.0.0-beta9
