### ISSUE TITLE
Gallows Hall CC entrance is blocked

### ISSUE THREAD

**Issue by Captain-Staky** [Guitarninja2/septimus#167]
![2021-12-28 11_44_52-Skyrim Special Edition](https://user-images.githubusercontent.com/44516691/147592996-4d5d9837-dfad-4aa5-8514-ec98e3c1b20d.png)

**Comment by Guitarninja2** [comment]
This is delayed until level 35 by this mod:
https://www.nexusmods.com/skyrimspecialedition/mods/60761
