### ISSUE TITLE
Easily Obtainable Creation Club Quests and Items at low level. 

### ISSUE THREAD

**Issue by Icantstopmoddinghelp** [Guitarninja2/septimus#17]
If this sounds like a patching nightmare, then just close this thread, because it is. I am simply baffled at the amount of stuff at low level. If you want to patch it, please be my guest.

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Myrwatch Easy to get mage house. The house can be accessed by a dead dude in front of it with a mage spell. Got it at level 4, has a lot of loot, but no armor or anything like that, like spells that can make you op

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Saints_%26_Seducers 
 I was able to start this at a very low level by finding the random saints bandits camp in Whiterun hold, they got op armor and etc. I also found another camp in Windhelm hold, with the dark version of the gear, op too. Can be accessed at level 1

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Bow_of_Shadows This dropped for a guy at level 3 in the discord.

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Hendraheim You can get this by killing the npc in front of the house, you do get a quest for it at level 10 however. That can be bypassed.

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Elite_Crossbows I was able to get this at level 2, by a quest I found at an bandit camp, in solitude

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Alternative_Armors_-_Ebony_Plate  - Heart of Crimson Quest, Ebony armor at level 1

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Alternative_Armors_-_Dragonscale  Titled Scales, level 1 dragonscale set

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Staff_of_Hasedoki found the quest for this at level 4, in whiterun bandit camp

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Alternative_Armors_-_Dragon_Plate got this at level 3 via quest - Bones for a Crow

**Comment by Icantstopmoddinghelp** [comment]
https://en.uesp.net/wiki/Skyrim:Headman%27s_Cleaver Got the quest for this at level 1

**Comment by Gyzarus-Selene** [comment]
https://en.uesp.net/wiki/Skyrim:Goldenhills_Plantation Easily obtained by killing two ghosts with less stats than a bandit thug and doing a short quest. Without upgrades gives the player access to a large number of hearthfire plots.

**Comment by Guitarninja2** [comment]
Finally fixed with a new mod!
