### ISSUE TITLE
[2.0] Missing Dialog to Purchase "Loft" in JK's The Winking Skeever Overhaul in Solitude

### ISSUE THREAD

**Issue by rfizzle** [Guitarninja2/septimus#171]
Seems a dialog is missing to purchase the key to a new Loft inside the Winking Skeever, which was added by JK's The Winking Skeever overhaul.

![WinkingSkeeverLoftKey](https://user-images.githubusercontent.com/2577744/147624069-5e390e0c-c4de-4d63-99d7-6322cfc1434c.png)

**Comment by Guitarninja2** [comment]
Fixed in beta 10
