### ISSUE TITLE
Mannimarco Shrine Blessing not working (Pilgrim)

### ISSUE THREAD

**Issue by PaulVys** [Guitarninja2/septimus#172]
The Fortify Conjuration Cost buff (Your Conjuration spells cost 10/20% less) 
gained from the Shrine of Mannimarco (Brittleshin Pass) 
seems to not reduce the cost of conjuration spells.

Tested with spell: Conjure Dremora Warrior (Mysticism).

**Comment by Durgenage** [comment]
I was testing this a bit earlier. All I can do is confirm that the spell cost reduction does not work. If you have 2 points in the Cultist perk, however, the 2 extra reanimations portion of the blessing DOES work as intended. I couldn't find any other mentions of this bug on the Pilgrim modpage or in Simon's discord, making me think that it's a conflict with Septimus, but I didn't see anything obvious in xedit.
