### ISSUE TITLE
Konahrik's accouterments mod suggestion

### ISSUE THREAD

**Issue by LoneBrian** [Guitarninja2/septimus#175]
Hey guitarninja! I've been playing septimus 2 and have been absolutely loving it so far. There is a mod I'd like to suggest as I feel it fits pretty lorewise and close to vanilla, and that would be kohnariks accouterments. I understand if there is some reason it can't be added, if maybe it screws with a geographical location or another dragon priest mask mod you prefer to have in the list. Crossing My fingers in hopes it will make it in to a later update, though!

Thank you again!

**Comment by Guitarninja2** [comment]
I will be looking into this in a future update yeah.
