### ISSUE TITLE
Bloodchill Manor Blocked by terrain

### ISSUE THREAD

**Issue by rheabutt** [Guitarninja2/septimus#18]
The bloodchill manor CC content is blocked by a patch of terrain
Pictures of the terrain, the entrance, and location on the map
![20211123162734_1](https://user-images.githubusercontent.com/44508315/143139781-3493059c-3b0a-44a6-b62c-f5cd460cb5d3.jpg)
![20211123162742_1](https://user-images.githubusercontent.com/44508315/143139784-e7bbb0d4-e7b4-4d5f-8b06-85a1dc7e5531.jpg)
![20211123162916_1](https://user-images.githubusercontent.com/44508315/143139790-19f1615e-36a7-4944-ac25-1e814e1016ce.jpg)
n,

**Comment by Guitarninja2** [comment]
Which version are you on? This should be fixed in the newest version.

**Comment by rheabutt** [comment]
1.6.2, made a new save to double check and the wall is still there

**Comment by rheabutt** [comment]
Just checked and apparently it's because inigo uses the same cell for his questline, there's a patch though https://www.nexusmods.com/skyrimspecialedition/mods/58317

**Comment by Guitarninja2** [comment]
Ah okay. Thank you!

**Comment by Guitarninja2** [comment]
And really appreciate the report.

**Comment by Guitarninja2** [comment]
Ok actually fixed in 1.6.3
