### ISSUE TITLE
Lake Illinata - Temple of Arkay

### ISSUE THREAD

**Issue by Tarzier** [Guitarninja2/septimus#191]
Temple of Arkay and some grass are floating a bit
![enb2022_1_1_16_32_42](https://user-images.githubusercontent.com/79779990/147860666-43664c77-37fb-4630-adc2-eb0a6d754b45.png)
![enb2022_1_1_16_32_57](https://user-images.githubusercontent.com/79779990/147860667-d0a89d02-ba28-499a-80a7-3342481690a2.png)
.

**Comment by Guitarninja2** [comment]
This should be fixed in 2.1.1 now
