### ISSUE TITLE
Missing Chairs in camp beside Inn at Kynesgrove

### ISSUE THREAD

**Issue by jtwalt** [Guitarninja2/septimus#192]
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 01 - 16 43 56 26](https://user-images.githubusercontent.com/69683677/147862472-96b48a7f-de17-41f3-b81a-3fd1e4699396.png)
Gemma Uriel
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 01 01 - 16 44 37 01](https://user-images.githubusercontent.com/69683677/147862474-cba85905-766b-4de0-b0f1-b71c644a6676.png)

 Gemma Uriel and others at the camp near the Inn at Kynsegrove use missing chairs.

**Comment by Guitarninja2** [comment]
This should be fixed now in 2.3.5
