### ISSUE TITLE
Game fails to launch

### ISSUE THREAD

**Issue by lotqahnaarin** [Guitarninja2/septimus#197]
I am here on behalf of a friend, who is tired of trying to make this work. I am here because I enjoy this modlist and would like to help him.

originally, when my friend installed and tried to run this modlist, he was on Windows 11. He was able to launch the game, but it would crash every time he left Helgen. We did some troubleshooting steps like enabling performance mode and reinstallation of the pack. We did some looking and discovered that some mods will not work on Windows 11, and so my friend and I concluded that maybe the issue stems from that. He "downgraded" from Windows 11 back to Windows 10, and restarted the process. He has several times had issues with downloading Skyrim Realistic overhaul part 1, but the suggested fix of restarting the download fixed that for him. After much patience, he eventually finished the installation. When he opens MO2, everything looks in place, when he presses play, MO2 will lock, the bottom progress bar will rapidly fill, then it will unlock, completely failing to execute Skyrim. This is frustrating because it is a multiple-day ordeal between downloading and troubleshooting. I haven't found much online dealing with this issue, can anyone here provide support?

**Comment by Guitarninja2** [comment]
Try turning off the reshade. It's probably that.

**Comment by Guitarninja2** [comment]
If you need help troubleshooting you really want to come by the discord here: https://discord.gg/xCPxJFbCTS
. It would take forever to troubleshoot something on github.
