### ISSUE TITLE
Packed BSA Wondering

### ISSUE THREAD

**Issue by Foamimi** [Guitarninja2/septimus#198]
Hello! I was curious to see if the following mods could be packed into BSAs to help reduce loading time:

- Vigilant Hi-Res Pack
- Darkend
- Interesting NPCs (except the "Music" folder)
- Beyond Skyrim - Bruma Upscaled Textures
- Citizens of Tamriel
- Cleaned Skyrim Textures (in addition to the current BSAs)
- Common Clothes Upscaled Textures
- Interesting NPCs - character Zora Fairchild's voice boosted (only if 3DNPC gets packed)

**Comment by Guitarninja2** [comment]
Packed most of these up. Thanks!
