### ISSUE TITLE
1.10.2 missing mods for consideration

### ISSUE THREAD

**Issue by natelovesyou** [Guitarninja2/septimus#199]
Per your request on Discord, here are mods that are missing since the 2.0 update that have stood out to me. They're from 1.10.2_to_2.0.0_modlist_comparison.html that I sent on 2021/12/31 1:11 AM MST in a direct message.

Consider this a heads-up, not necessarily a request. These are mods that are either good visual changes, or mods/plugins I think should get a second pass (such as Boethia for Good Guys that was skipped).

[Adamant - Plus Ten Smithing] - ("This plugin spreads the Vanilla tempering tiers across ten levels (+1, +2, +3, etc), which provides a smoother power progression for Smithing.")
[Alik'r Warriors Aren't Welcome]
Andrealphus' Tweaks - Harder Quests - Harder Mara Quests]
[Andrealphus' Tweaks - Harder Quests - No Easy Bloodkin]
[Antiquary - Enhanced Artifacts] + 2 patches
[Arctic - Frost Effects Redux]
[Argonian Weight Slider Affected Tails]
[Authentic Eyes] - possibly something already better?
[Better Dynamic Ash]
[Better Dynamic Snow] 
[Boethia for Good Guys]
[Bounties Are Worthwhile - Leveled Bounty Rewards] - these bounty changes seem nice, but possibly something better is in?
[Bounty Preview]
[Calcelmo Has Standards] - small change, nearly insignificant
[Classic Paralysis] - nice addition instead of the silly animation in vanilla, and has a fix to animations
[Cleaned Creation Club + Anniversary] 
[Cliff Racers on Solstheim] - maybe this wasn't lore-friendly? IDK
[Companions Werewolf Bloodritual Scene Tweak] - fixes Bethesda silliness, somewhat
[Contraband Confiscation] - nice tweak that makes Human Hearts, Skooma, and other sketchy items get confiscated with stolen goods when jailed
[Deadly Spell Impacts] + [Deadly Spell Impacts Transparency Fix for ENB]
[Delphine's Map Reveals Dragon Mounds] - sounds like a nice change, perhaps skipped on purpose
[Dismiss Steward] - possibly covered by NFF or something else?
[Dynamic Volumetric Lighting and Sun Shadows] - super nice improvement
[EMPEROR - Giant Crab Overhaul] - Nice fixes for the Fishing CC boss
[Enhanced Reanimation] and [Faster Reanimation] - great for conjurers
[Favorite Things - Extended Favorites Menu for SkyUI] - possibly replaced?
[First Person Camera Height Fix] 

(That's as far as I've gotten so far)

**Comment by Durgenage** [comment]
This looks familiar

**Comment by Guitarninja2** [comment]
We're doing round two to see if I missed anything else major lol
