### ISSUE TITLE
A Giant's Slayers Guide to Giantology

### ISSUE THREAD

**Issue by BroTechNY** [Guitarninja2/septimus#20]
![1](https://user-images.githubusercontent.com/9996171/143162882-a4cca568-f7f4-4fc9-af54-0b357a7544d5.png)
![2](https://user-images.githubusercontent.com/9996171/143162883-fc2512fa-567a-440b-bef7-94a6aeae3c69.png)
![3](https://user-images.githubusercontent.com/9996171/143162885-f758a2dd-1373-467b-b7e6-f09ff08895a4.png)

**Comment by Guitarninja2** [comment]
Fixed in 1.6.4
