### ISSUE TITLE
[2.0.1] Greybeards and Mannequins do the cold/nude conditional animation unnecessarily.

### ISSUE THREAD

**Issue by DarkElfMagic** [Guitarninja2/septimus#205]
The “Conditional Idles” mod seems to apply to the greybeards unnecessarily, and gives them the nude/cold animation when they do not meet the requirements for those animations, nor is it at an appropriate time since it’s a big cutscene

Also the mannequins in “Blackthorn” are also under a similar effect of having the same idle animation unnecessarily placed upon them.

**Comment by Guitarninja2** [comment]
This will be fixed in 2.0.2
