### ISSUE TITLE
Fortune´s Tradehouse Basement Master level spellbook

### ISSUE THREAD

**Issue by Recoveres** [Guitarninja2/septimus#207]
In the Basement of the Tradehouse mod there was a Masterlv. summon Dremora Lord book in the room with the Pi"per and the Skeever Matriach it might be a bit much for a quest where you only need to kill lv.16 mobs .
To be specific the book lays on the enchanting table in the last caver of the basment tunnel system

**Comment by Guitarninja2** [comment]
Fixed in 2.1.1
