### ISSUE TITLE
ClefJ's Dawnguard Tower Dissapears if you enter through the pass

### ISSUE THREAD

**Issue by ScornfulBadge** [Guitarninja2/septimus#220]
![Skyrim Special Edition 1_9_2022 10_16_47 PM](https://user-images.githubusercontent.com/97426809/148722606-e2af6c66-588a-4353-acfd-ed4bb3d914e2.png)

**Comment by ScornfulBadge** [comment]
My personal fix is to unflag ClefJ's Fort as a esm but still leave it flagged as esl

**Comment by Guitarninja2** [comment]
This is actually an issue with dyndolod it seems. Just need to re-run it.

**Comment by Guitarninja2** [comment]
Should be fixed in the latest 2.1.1 now
