### ISSUE TITLE
ESPFE Wonderings

### ISSUE THREAD

**Issue by Foamimi** [Guitarninja2/septimus#223]
Hello! I was wondering if the following .esps could be flagged as .espfe files in one of the upcoming updates, as all would be safe to do so without needing to be compacted:

- SKYUI
- Landscape For Grass Mods - Military Camps
- ChargeDialogueFix
- Dawnguard Dont Hunt Cured Vampires
- Move it Dammit - Less Wait Time and Follow Me Closer
- Runandwalkpaces
- No NPC Greetings
- Don'tTalkWithYourMouthFull
- dD-No Spinning Death Animation Merged
- Sparkles
- RaceMenu
- Eli_CLBladeOfWoePatch
- Darkend Balance Patch
- BS Bruma Patch
- SMIM-Bruma-Patch
- VIGILANT CC Armor
- LovelyLetter
- CompanionsTweaks
- Companions - Don't be a Milk Drinker
- survivalmodefasttravel
- SurvivalModeImproved_Wyrmstooth
- Realistic Melee Range
- Improved Traps
- WindhelmSegregation
- VWA_VanillaWarpaintsAbsolution
- KhajiitsStealToo
- Cloaks - USSEP Patch
- 1nicvWICSkyCloaksPatch
- Survival Mode Patches - Cloaks Of Skyrim
- Survival Mode Patches - Winter Is Coming
- Nordic Carved Light
- FNIS

**Comment by Guitarninja2** [comment]
Many of these have been flagged :D
