### ISSUE TITLE
Vigilance Reborn and Meeko Reborn

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#224]
Two issues:
- Vigilance Reborn and Meeko Reborn need to be above Dream's Unique Dogs in the load order.
- Vigilance Reborn and Meeko Reborn are supposed to be essential followers, but they are dying.

I have no mods installed other than 2.2.0, and have the following optional mods active on the AE profile: Dragonborn Dreams, FEC, Sidequests of Skyrim, LOTD, LOTD CC, Fast Travel, VHR, and Positive Undressed Reactions. Both times the dogs have been killed in fights with a bandit chief who may be doing AE attacks.

**Comment by Guitarninja2** [comment]
Fixed in the next update. Thanks!
