### ISSUE TITLE
Object culling glitch

### ISSUE THREAD

**Issue by TamerasBreyr** [Guitarninja2/septimus#227]
I found an invisible volume around a tree (possibly belongs to it) near the Riverwood lumber mill that causes object culling. Fresh install, only Septimus content, new character.
![objectculling_glitch](https://user-images.githubusercontent.com/97667316/149304912-139d6125-af7f-462e-ac4c-47e255ea4df0.JPG)
![objectculling_glitch_location](https://user-images.githubusercontent.com/97667316/149304914-e8891970-1c7d-40e8-b7fa-4b9ab127ca10.JPG)

**Comment by Guitarninja2** [comment]
This is due to the tree mod I use being a bit smaller than what eFPS boost expects. I can't really do much about it. It only really happens when very close to the tree though.

**Comment by TamerasBreyr** [comment]
Fair enough. I probably wouldn't have even been around the place long enough to notice it if I hadn't gone with the (shortened) vanilla start.
