### ISSUE TITLE
ASLAL - Issues Thread

### ISSUE THREAD

**Issue by Phoenix96ace** [Guitarninja2/septimus#228]
Found a LOTD relic fairly strong in an Adept Lockbox in the Warlock start

![SkyrimSE_lYhWzykjHC](https://user-images.githubusercontent.com/38291029/149594253-c4b0c294-6b0a-446e-a704-a5361a8a98a1.jpg)
![SkyrimSE_igYYAsb2MF](https://user-images.githubusercontent.com/38291029/149594261-82895bd7-f91f-47ed-bbde-27c250bbb649.png)

Location: Cragwallow Slope
Map: 
![SkyrimSE_JXeMmXtYp5](https://user-images.githubusercontent.com/38291029/149594348-45ae9a25-e847-45a2-b914-b92d8c468ab2.jpg)
.

Another ring - Necromancer in a Secret lair start [not as powerful but still a lotd relic right off the bat in an unlocked box]
![SkyrimSE_zdPuBPNlQT](https://user-images.githubusercontent.com/38291029/149599128-26d5cdc2-5ee8-4d5d-934f-5ae76aadb666.png)

Location: blackreach

Not LoTD and not super op but figure it worth mentioning, the start to escape the prison allows you to get kaiden immediately and a full set of elven gear (tested twice on 2 new saves both had elven)

**Comment by Webmetz** [comment]
I would say lock the Ring of the Mentor in a Master Level Box, and Jewler of the Rumae in an Expert Level lock.
