### ISSUE TITLE
Water glitch near Little Vivec

### ISSUE THREAD

**Issue by lRodz** [Guitarninja2/septimus#233]
Coords "Tamriel -7 -16"

![20220118233205_1](https://user-images.githubusercontent.com/98000915/150053506-61181e20-cc26-4244-8d7f-9fecc452b2b6.jpg)

**Comment by lRodz** [comment]
![Untitled](https://user-images.githubusercontent.com/98000915/150179996-23b26885-f7a9-4b6e-a021-534994babd3a.png)

**Comment by Guitarninja2** [comment]
This should be fixed now.
