### ISSUE TITLE
Serana Revamped - Quests Are in Skyrim Conflicts

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#234]
![image](https://user-images.githubusercontent.com/2394842/150056971-403c3df7-9afe-46b0-9d27-88193e7f69ca.png)
Hide and Seek
![image](https://user-images.githubusercontent.com/2394842/150057001-94e646cd-7dc6-474e-a994-684749212c76.png)
Hunting the Monster / Ancient Technology
![image](https://user-images.githubusercontent.com/2394842/150057039-6390523c-045d-4c4c-9367-640db7b7ef6f.png)

**Comment by Guitarninja2** [comment]
I put your patch in for 2.3.5. Good to go now.
