### ISSUE TITLE
[2.3.4] Crash on fast travel using Cyrodiil alternate start

### ISSUE THREAD

**Issue by ShakesShakes** [Guitarninja2/septimus#236]
Fast travel goes to a black screen and locks up the PC. This only happens on characters I make with a Bruma start, Skyrim ones can fast travel fine.

**Comment by Guitarninja2** [comment]
Yeah I'll likely remove the cyrodiil start. The encounter zones are not leveled for starting characters anyway.

**Comment by Guitarninja2** [comment]
Remove in 2.3.5
