### ISSUE TITLE
Goldenhills Plantation Moon Sugar

### ISSUE THREAD

**Issue by K3es** [Guitarninja2/septimus#242]
At Goldenhills Plantation there are 44 plantable zones, at each of these you can plant something, normally you'd plant Blisterwort because it's worth 12 per piece, by far the most profitable growable for Goldenhills Plantation.
I don't know which mod allows you to plant Moon Sugar, but it's worth 50 per piece, giving you about 4000 gold coins every 2 days plus a ridiculous amount of Moon Sugar from the Pantry and be manually harvesting it.

When you harvest the Moon Sugar plant it shows that you harvested 3 Worm's Head Cap.

**Comment by Guitarninja2** [comment]
Fixed in 2.4.0 :dogsmile:
