### ISSUE TITLE
Embers HD - Cooking in Inns Conflicts

### ISSUE THREAD

**Issue by lRodz** [Guitarninja2/septimus#244]
Misplaced fire

![20220120211459_1](https://user-images.githubusercontent.com/98000915/150442825-ac7feef2-0992-420f-983f-ec0cc4d21ce6.jpg)

![Untitled](https://user-images.githubusercontent.com/98000915/150442719-8fe53768-1047-402c-ac45-3d8eeaf9966c.png)

**Comment by Guitarninja2** [comment]
😬

**Comment by Guitarninja2** [comment]
Fixed in 2.4.0
