### ISSUE TITLE
Twin enchantment perk possible bug

### ISSUE THREAD

**Issue by Epyrus1991** [Guitarninja2/septimus#246]
It lets you triple enchant items instead of the usual two. Works on every type and it's not restricted to a single time triple enchant like the "miracle" perk.
![image](https://user-images.githubusercontent.com/69695995/150658830-063f59aa-f7f3-4ddc-83aa-5e94fb0d3ace.png)
![image](https://user-images.githubusercontent.com/69695995/150658833-de5899d8-45e4-483e-85d2-c66aad23ce51.png)

**Comment by Guitarninja2** [comment]
Found the issue. Should be fixed in 2.3.6
