### ISSUE TITLE
Unhandled native exception (v2.2.0)

### ISSUE THREAD

**Issue by TamerasBreyr** [Guitarninja2/septimus#248]
I realize that this might be an issue at my end but, then again, it might not. I have 2.2.0 installed, no extra mods, the only customized bit is the ReShade preset tweaked to my liking.
(You probably moved on to 2.3.x but I am reluctant to do so as I have about 53 hours in the playthrough. If it's something you can't be bothered with, fair enough, just close this thread.)

I've started having crashes to desktop without any pop up. They can be reliably reproduced on demand and always produce a crash log in MO2 very similar to [this one that I just pasted on Pastebin](https://pastebin.com/ds39Tykb)
The first line is always the same (apart from the thread number), just as the first couple of possible relevant objects are the same FormID belonging to an animal, if not a 'Wolf' then a 'Stag' or something.

This is one spot where it has been happening, at the top of that incline just ahead. (West of Whiterun/Watchtower) So far it has only happened in the general area around Whiterun.

![SkyrimSE 2022-01-23 09-24-06](https://user-images.githubusercontent.com/97667316/150672979-823ca254-cbd7-411d-9640-f83be436d724.jpg)
![SkyrimSE 2022-01-23 09-23-56](https://user-images.githubusercontent.com/97667316/150672984-00f1643c-3bbc-4663-8d1c-023c91530756.jpg)

**Comment by Guitarninja2** [comment]
Unfortunately something was causing these in older versions. Are many, many hours of investigating I was not able to track it down. In 2.3 though, this should be resolved.

**Comment by TamerasBreyr** [comment]
Well, I tried loading an earlier save but the first one that didn't crash would have meant losing 40 hours of progress.
I ended up upgrading to the latest version and started a new game.

Thank you for answering.

**Comment by Guitarninja2** [comment]
Sorry about that yeah. It's unfortunate for everyone involved. Tried my best to resolve the issues in 2.2 but was unable to.
