### ISSUE TITLE
Good Dogs Don't Heal Between Battles

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#249]
I think Vigilance (and I think Meeko, and perhaps other pet companions) don't regenerate health outside of battle. This means that unless you remember to heal them, they often start the next battle with 1-2 health points. It would be great if they regenerated health between battles like other followers.

**Comment by w1LL-N** [comment]
Gladys wouldn't heal either

**Comment by Guitarninja2** [comment]
This should be good now.
