### ISSUE TITLE
Helgen Reborn & LOTD integration bug

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#250]
This is probably a bug in Helgen Reborn and not Septimus, but just to document it: Having the Black Glass Claw from Helgen Reborn in your inventory causes using the LOTD museum display auto-sorter to CTD. Attached is a crash log. This is totally repeatable, at least on my playthrough.

[Crash_2022_1_24_18-19-33.txt](https://github.com/Guitarninja2/septimus/files/7929969/Crash_2022_1_24_18-19-33.txt)

I do have both Helgen Reborn and Helgen Reborn - LOTD integration enabled. I enabled both after leaving Helgen. I started with the ASAL Guildmaster start.

**Comment by TavishTheDeaf** [comment]
Your load order being wrong might a contributing factor.

**Comment by rsrogers4** [comment]
> Your load order being wrong might a contributing factor.

I see. The Helgen Reborn mod and the DBM needs to be above the Septimus patches. At one point it was but maybe updating via WJ reset the position. Thanks. I’ll retry and close if that’s the cause.

**Comment by rsrogers4** [comment]
Eureka, that was it. Thanks @TavishTheDeaf.
