### ISSUE TITLE
Advanced Lab Trouble

### ISSUE THREAD

**Issue by TamerasBreyr** [Guitarninja2/septimus#253]
Hi,
I ran into an issue with the Alchemy Perk "Advanced Lab" whereby it doesn't seem to be granting its effect. The potions mixed are the same strength as if they were created at a regular Alchemy Lab and, as a result of the missing effect, the subsequent "Double Toil and Trouble" perk is also non-functional. At least, I think it is caused by the buggy "Advanced Lab". Even the visual upgrade to the lab seems to be hit or miss. I haven't touched the related setting in the MCM and sometimes it appears, other times it doesn't but the label always changes to Advanced Lab.
I tried upgrading both vanilla and mod-added labs but I found no difference in outcome.
I also tried searching for issues with Ordinator, itself, but my googling didn't turn up anything relevant. My limited experience with xEdit says it should be functioning as intended.

I hope I'm not the only one posting multiple and possibly non-resolvable issues. I'd hate to be a nuisance, especially if it's something trivial that I just missed.
Cheers.

**Comment by Guitarninja2** [comment]
Will take a look at this when I have some time. Thanks.

**Comment by TamerasBreyr** [comment]
Hey, 
Thanks for the reply.
Further testing suggests that it's the "Craftloot" system in Legacy of the Dragonborn that is interfering with the perks. I enabled it for every crafting station in the game and could immediately upgrade the lab after I deactivated it in the MCM, with every perk working as expected.
When you have the time, you might want to start looking there first.
I've left comments about this on both Ordinator's and LotD's comment page on nexusmods. Just maybe there is a solution that you can simply add to Septimus in a next update instead of working it out yourself.
Cheers

**Comment by TamerasBreyr** [comment]
So apparently there is a FAQ item for LotD dedicated to the incompatibility between Craftloot and the Advanced Lab and related perks in Ordinator.
The LotD guys also said to turn off Craftloot as a solution... Meh. They basically told me they can't fix it without telling me they can't fix it.

It means I posted another dud for you. Sorry, mate.
