### ISSUE TITLE
Frost spell (After effects)

### ISSUE THREAD

**Issue by SpaghettiExcuse** [Guitarninja2/septimus#254]
![image](https://user-images.githubusercontent.com/96251729/151423959-7aeb27a3-7b0f-4bf8-9346-1a5dbf495253.png)
![image](https://user-images.githubusercontent.com/96251729/151423988-4cac9907-0122-4227-9f29-b1c668e57acb.png)
In these two images I used the spell artic blast, which is an Odin spell, and the after effects that should be there, from the mod Arctic - Frost Effects Redux are not (https://www.nexusmods.com/skyrimspecialedition/mods/29817).
I checked the vanilla Frostbite novice spell and the effects don't seem to be working on that either. 
![image](https://user-images.githubusercontent.com/96251729/151424677-4f26bc6c-44a5-455b-86ca-84bd3a6cc559.png)

Sorry if this is just my skyrim being wonky and not an actual issue.

**Comment by Guitarninja2** [comment]
Will add deadly spell impacts so they look better.
