### ISSUE TITLE
Duplicated Books due to BCS-Lost Library and LOTD

### ISSUE THREAD

**Issue by Scarlet-Stinger** [Guitarninja2/septimus#258]
LOTD incorporates BCS and Lost Library in the install. Lost Library stand-alone, as a result, is adding duplicated books to the world space.

Was raised on discord, but perhaps remove Lost Library from the install and then resolve conflicts with the following patches:

- OCW_BCS-LL_FEPatch.esp
- Septimus - Legacy of the Dragonborn.esp
- Septimus - Lost Library - Cloaks.esp

**Comment by Guitarninja2** [comment]
Removed Lost Library in 2.4.0
