### ISSUE TITLE
Power of Creation mods to replace bad CC items

### ISSUE THREAD

**Issue by Scarlet-Stinger** [Guitarninja2/septimus#262]
Migrating a reminder to this issue page from discord. 

Alno05 from Discord asked to Guitarninja to look into "Power of Creation" mods for 2.4 because "most of [the CC artifacts] are dogshit and the ones that are good are way too good"
![image](https://user-images.githubusercontent.com/98657035/152075236-80428b08-8fcd-4d7f-aeb4-6bf4f75286c2.png)

Nexus links below for your convenience:
[Power of Creation - Shivering Relics](https://www.nexusmods.com/skyrimspecialedition/mods/58438)
[Power of Creation - Fishing](https://www.nexusmods.com/skyrimspecialedition/mods/58354)
[Power of Creation - Necro Mastery](https://www.nexusmods.com/skyrimspecialedition/mods/58488)
[Power of Creation - Creation Club Overhaul](https://www.nexusmods.com/skyrimspecialedition/mods/58689)

**Comment by Guitarninja2** [comment]
Added to 2.4.0
