### ISSUE TITLE
Conjuration leveling very quickly

### ISSUE THREAD

**Issue by piranhamoe** [Guitarninja2/septimus#266]
I was using Lesser Reanimate while under the effect of The Ritual standing stone so I had 2 reanimated undead minions. Every time I entered combat with my 2 minions I gained about 5 levels of Conjuration, an amount that seems a bit too much. This was a level 3 character, started with Conjuration of about 20, ended with Conjuration at about 50 just going through White River Watch.

**Comment by Guitarninja2** [comment]
Should be fixed in 2.4.0 beta 2
