### ISSUE TITLE
Floating Packs and Lantern outside Valdr's House in Falkreath [2.4 Beta1]

### ISSUE THREAD

**Issue by 4ulender** [Guitarninja2/septimus#268]
![20220206115504_1](https://user-images.githubusercontent.com/96638017/152691812-5412de54-364c-413e-aacd-630234f27c32.jpg)

There are floating packs and a lantern outside the new house outside Falkreath added by BUVARP for Valdr. I suspect these were on the carriage and this is an issue between BUVARP and the Carriage mod.

**Comment by Guitarninja2** [comment]
Yeah the CFTO patch for BUVARP doesn't include the optional addon stuff. I'll fix it myself.

**Comment by Guitarninja2** [comment]
Fixed for 2.4
