### ISSUE TITLE
Auri face is brown

### ISSUE THREAD

**Issue by broodwarjc** [Guitarninja2/septimus#27]
https://www.nexusmods.com/skyrimspecialedition/mods/11278?tab=description

I have a fresh install and no additions to your mod list, but I have encountered this issue: Auri's face is having the brown face problem. Is there a patch needed for a NPC texture replacer that got missed?

**Comment by Guitarninja2** [comment]
Probably just a small conflict. Should be an easy fix. I'll take care of it in the next update.

**Comment by Guitarninja2** [comment]
I'll be including this: https://www.nexusmods.com/skyrimspecialedition/mods/36444 in the next release and I've tested she looks good so we should be good to go then

**Comment by Guitarninja2** [comment]
Temporary fix for now is this though: https://www.nexusmods.com/skyrimspecialedition/mods/42441
