### ISSUE TITLE
Broken Courier

### ISSUE THREAD

**Issue by MPRATCH-V2** [Guitarninja2/septimus#270]
I haven't seen the courier since maybe around level 5 I'm now level 17. He didn't show up for the dark brotherhood quest line but I was still able to proceed when I went to sleep I was kidnapped even though I never received the letter. The dragonborn museum was supposed to give me a key to the saferoom through him but he never showed up to give it to me even though I meet the requirements. There is surely more that he needs to give me but I don't have specifics on what I'm missing. Not sure what caused this but I've tried "prid 00039fb7" "moveto player" and I also tried "player.moveto 00039fb7" if I use player.moveto after using moveto on the courier to teleport him to me it will teleport me a few feet away where I attempted to teleport the courier to me. No dead body or anything he seems to have just been disabled. As far as I'm aware there are no mods in this pack that should replace or overwrite the courier but I very well could be mistaken.

**Comment by Guitarninja2** [comment]
No one else has seen this. I'll have someone else re-open the ticket if it happens again.
