### ISSUE TITLE
Missing name 2.3.6.2

### ISSUE THREAD

**Issue by ItsMeChase** [Guitarninja2/septimus#272]
Missing name on elevn armor, even tho i dont have perk point put in elevn crafting!
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2022 02 08 - 17 52 17 73](https://user-images.githubusercontent.com/97307129/153030269-9bc0f0c6-d233-4429-8137-777e6c90aaeb.png)

**Comment by Guitarninja2** [comment]
No idea what's going on with this.
