### ISSUE TITLE
Character Creation Recommdations 

### ISSUE THREAD

**Issue by Icantstopmoddinghelp** [Guitarninja2/septimus#28]
List has been great but the character creation is quite lacking in many areas.
https://www.nexusmods.com/skyrimspecialedition/mods/20183?tab=description I have added this mod in every list I have used. I have ran with it fully on yours for the total time I have played with no problems. It can be eslifed too. Works on men

https://www.nexusmods.com/skyrimspecialedition/mods/12004/ Immverisve KS Hairdos is a good compromise, I know you don't like how fake some of the hair looks, but it can be fixed with salt and wind retexture. I actually ran fully with Ks Hairdos on your list too with no issues. 

https://www.nexusmods.com/skyrimspecialedition/mods/52336 Salt and Wind retexture. Might need to use old one, Idk. (1.7 one )

Heck, these two mods are enough to create decent look characters that are unique. I have only been using these two, but I will suggest some other stuff.

Luckily the addons I suggest minus the hair come from same guy, so his/her stuff is stable.
https://www.nexusmods.com/skyrimspecialedition/mods/22487, Works great, and adds a little bit more with paints. Works on men too :D. 
https://www.nexusmods.com/skyrimspecialedition/mods/26224 community overlays 2,
https://www.nexusmods.com/skyrimspecialedition/mods/35339 overlays 3.

I think if you add these mods, and the list will look at lot more beneficial to people who like character customization. I really don't want to add mods, but have too, cause vanilla character creation doesn't make my dragon born unique. I know living Skyrim, Librum, and some other big lists use these overlay mods. I know that don't mean they are stable, but haven't been removed yet?

**Comment by Guitarninja2** [comment]
For now I don't think many of these are necessary
