### ISSUE TITLE
Scroll crafting station doesn't allow crafting of non-vanilla spells

### ISSUE THREAD

**Issue by godvivec1** [Guitarninja2/septimus#280]
![scroll craf](https://user-images.githubusercontent.com/99567950/153734500-4bac2de1-c69f-4598-8da1-d5dc19acb4e4.png)
![inventory](https://user-images.githubusercontent.com/99567950/153734508-ddebe02f-1d6e-4399-b0df-0c6695f02a4a.png)

**Comment by Guitarninja2** [comment]
This is a known thing with the mod.
