### ISSUE TITLE
Weird Interaction between 3DNPCS and an Alternate Start option [2.4.0]

### ISSUE THREAD

**Issue by DarkElfMagic** [Guitarninja2/septimus#281]
The option in alternate start "I'm a warlock's thrall..." has a weird interaction with 3DNPCs, where the necromage altmer is supposed to be dead before you get in there, but Alternate start puts you past the trigger that makes sure the necromage is dead. When you talk to the argonian, the 3DNPC added by the 3DNPC mod, the necromage attacks him bc the necromage isn't supposed to be alive.

The best solutions are either remove the option in alternate start, or make sure the altmer is dead when you choose that option.

**Comment by Webmetz** [comment]
http://3dnpc.com/wiki/interesting-npcs/locations/the-rift/among-the-hist/
He is a potential follower and part of a quest 
I suggest making him protected.
