### ISSUE TITLE
CC “Elite Crossbows” gives player access to powerful weapons, armors and bolts at level 1. [2.4.0] [Balance Issue]

### ISSUE THREAD

**Issue by DarkElfMagic** [Guitarninja2/septimus#283]
At level one, a player can go just south-ish of the thalmor embassy, to find and activate the quest “Night Hunter” added by the Creation Club add-on “Elite Crossbows”

This quest can be found at Level 1, and following the quest to it’s completion leads to a Elven Crossbow AND a Ebony level crossbow, along with many dwarven elemental bolts, prtty powerful armor and weapons for level 1 (I found some orcish peices.) 

This wasn’t hard to get to as I had started around that area with the “Alternate Start - Live Another Life” mod.

**Comment by Guitarninja2** [comment]
This should be solved in the newest update.
