### ISSUE TITLE
Clipping at Nightgate Inn

### ISSUE THREAD

**Issue by Glimmer-Mandy** [Guitarninja2/septimus#287]
It's clipping between a cooking pot added by Cooking in Inns and a small structure added by Distinct Interiors at the Nightgate inn. Nothing major.
![20220218230014_1](https://user-images.githubusercontent.com/56629380/154745977-c0198a2d-0f3b-4b3e-aee9-bb4f3fdb733c.jpg)

**Comment by Guitarninja2** [comment]
Fixed in 3.0
