### ISSUE TITLE
A Night to remember Quest Septimus 2.4.0 

### ISSUE THREAD

**Issue by ThanosXBL** [Guitarninja2/septimus#291]
Talked to Sam and drank 3 times. (DA14START) completes but does not black out/progress to the markarth temple (DA14).
Senna, Ennis and Ysolda are alive. Completed Forsworn Conspiracy as well as Heart of Dibella and still no dice 😔 

(No added mods) (Akatosh Chosen Alternate Start)

**Comment by Guitarninja2** [comment]
I am looking into this one now. It's a tough one but we're on it :)

**Comment by Guitarninja2** [comment]
Fixed in 3.0 :D

**Comment by Guitarninja2** [comment]
Oh if you want to fix it in the version you're playing just turn off the mod "coven"
