### ISSUE TITLE
[Landscape conflict] : During Ghosts of tribunal, Entrance to secret temple is not accessible

### ISSUE THREAD

**Issue by dip4k** [Guitarninja2/septimus#295]
![Septimus_2 4_SS142](https://user-images.githubusercontent.com/30719351/157116156-4ba572af-8a8d-43dd-8ce2-51ed428f9c34.png)
![Septimus_2 4_SS141](https://user-images.githubusercontent.com/30719351/157116165-b44899d0-7085-40e6-83d8-61d024617d14.png)

**Comment by Guitarninja2** [comment]
Fixed
