### ISSUE TITLE
micmou's Random noticed bullshit

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#297]
This issue is going be where I put all the minor issues I find that could be under the classification of RANDOM BULLSHIT.

**Comment by micmou** [comment]
First Random Bullshit
Bleak Falls Barrow before the two bandits that are talking about sir happy feet in the basement
https://i.imgur.com/exG8hvT.jpeg

part of the floor is see through.

**Comment by micmou** [comment]
Another one. The Curators Companion Icons are slightly askew
https://i.imgur.com/OgCh2Dr.jpeg
When picking items up from the world

**Comment by Guitarninja2** [comment]
Thank you for doing this btw.

**Comment by micmou** [comment]
Practice Crossbow and Bow do not award XP and the Practice Bolts convert to hunters bolts upon being picked up.
https://i.imgur.com/l55Ka1V.jpg

**Comment by micmou** [comment]
People Training archery in the Thieves Guild are shooting some form of fire arrow. It is super loud and distracting specially mid convorsation with quest NPCs. NTM the fire hazard think of the rats T-T
https://i.imgur.com/QUGog4g.jpg

**Comment by micmou** [comment]
Some mod is given a bunch of arrows to various enemies with bows I suppose this is directly causing the previous issue as well
https://i.imgur.com/GpvOAIN.png

**Comment by micmou** [comment]
LSC Seems to have placed very strong weapons in easy to get locations like the one below being avliable as soon as you walk through the door to the Dark Brotherhood
https://i.imgur.com/cpVW7Nl.png

**Comment by micmou** [comment]
World seam in windhelm on the left side distrect when facing the main building.
https://i.imgur.com/KOEp85x.jpg

**Comment by micmou** [comment]
Inigo Duplicate items in his inventory
https://i.imgur.com/CbGyFGJ.jpg

**Comment by micmou** [comment]
LSC (again)
Arrow one shot me from level one bandit.

**Comment by micmou** [comment]
Dynamic Things has the crate the night mother arrives in be searchable
https://i.imgur.com/SC4tdsW.jpg

**Comment by micmou** [comment]
Enemies are vanishing after being killed in some cases not sure the cause nor am able to replicate reliably.
https://i.imgur.com/Sh4LCqg.jpeg

**Comment by micmou** [comment]
hole into void in the Volunruud Elder's Cairn by the wordwall
https://i.imgur.com/0Yf1shP.jpg

**Comment by micmou** [comment]
Vampire slayer in fort dawnguard is marked a steal
https://i.imgur.com/99xQGxL.jpeg

**Comment by micmou** [comment]
After absorbing master Einharh knowledge of Ro in dragons reach he becomes bloody
https://i.imgur.com/2OmQDqy.jpeg

**Comment by micmou** [comment]
Upon reading books/notes while being in a container the game sometimes locks your controls you can open the console and sound plays but nothing else.

**Comment by micmou** [comment]
Markarth city inside where the dwarven researcher is right after the start for the cannibal quest at certail angles we get some weird red/green strobbing
https://i.imgur.com/NXmTr5N.jpeg

This needs to be fixed ASAP it will legit end up killing someone IRL.

**Comment by micmou** [comment]
dewreck on discord found this lantern floating near rorikstead
https://i.imgur.com/R3VXpgf.jpeg

**Comment by micmou** [comment]
Floating Candle Helgen Keep
https://i.imgur.com/o2sz8VC.jpeg

**Comment by micmou** [comment]
Reported by Averos on github. Sign is clipping into wall
https://i.imgur.com/5ArNzWk.jpeg

**Comment by micmou** [comment]
Collision issues on a wall in solitude walk right through it
https://i.imgur.com/olVI6dM.jpeg

**Comment by micmou** [comment]
misplaced lantern at the bridge near little vivec reported by GunnZeug

**Comment by micmou** [comment]
No image with this one ill add it later.
Galdur amulet enchant description claims 30 health stam mag but gives the correct value of 50 health stam mag.
