### ISSUE TITLE
Vampires lose health as soon as I enter the cell

### ISSUE THREAD

**Issue by OmriSherman** [Guitarninja2/septimus#298]
Hey :) 
So I have this weird issue with vampires, the moment I enter the cell they are in, they start to lose health until they die.
I don't want to start Dawnguard like this cause im sure it will be bugged af :(

For example, the moment I entered the blue palace Sybille started to lose health until she died and became a pile of ash!

I was sent to bloodlet throne to kill Vighar and he 'died' when I only reached the second room! same as all the other vampires

I tried messing with the vampire mods but its clearly not the case, I am in need of a savior, please help!!

**Comment by Guitarninja2** [comment]
Is this Septimus 2.4? Also what profile? AE or normal?

**Comment by OmriSherman** [comment]
yes, septimus 2.4, skyrim AE

**Comment by OmriSherman** [comment]
![sybille](https://user-images.githubusercontent.com/76867526/158033298-74d10bb4-cf6b-4c86-80cc-8bed3af3924a.jpg)

@Guitarninja2 here is a screenshot of Sybille after I ran the recycleactor command, she is ok for a few seconds, than these blood stains appear on her, she is practically dying, only that I set her to be essential. 

If you will successfully help me solve this issue you can be sure that I'll show you my support for this amazing modlist. thanks!

**Comment by Guitarninja2** [comment]
I'm sorry I've never seen this happen myself. I don't actually know the cause. It's very difficult to track down as I can't make it happen in my game. I have seen reports of it happening when the creation club content was not set up properly.

**Comment by OmriSherman** [comment]
I see, well for the cc content I just copied the files from the /Data folder onto my septimus: mods\Official Creation Club - Free
folder, but the cc content seems to work fine.

**Comment by Guitarninja2** [comment]
Oh lol yeah there's your problem.

**Comment by Guitarninja2** [comment]
Please check the cc install instructions again. You need to be on the right profile. That's what causes the issue.
