### ISSUE TITLE
Immersive Interactions - Animated Actions 

### ISSUE THREAD

**Issue by Icantstopmoddinghelp** [Guitarninja2/septimus#3]
https://www.nexusmods.com/skyrimspecialedition/mods/47670

Any type of mod would work that can bring life to the player character. 
Doesn't have to be this one per say but it's pretty good.

**Comment by Icantstopmoddinghelp** [comment]
Mod is great but petting horses and doggos can be buggy as hell. Just ideas tho

**Comment by Guitarninja2** [comment]
In general I find this bug too buggy unfortunately. It does add some neat things but I'm probably going to hold off for now.
