### ISSUE TITLE
Mod suggestion: Know Your Enemy

### ISSUE THREAD

**Issue by Omrga** [Guitarninja2/septimus#30]
Know Your Enemy - Trait-based resistances and weaknesses is a great mod, because it makes you think a little more before running into battles. 

https://www.nexusmods.com/skyrimspecialedition/mods/13807

**Comment by Guitarninja2** [comment]
This seems to be a popular one. I'll give it a shot in the 1.7.0 beta.

**Comment by Guitarninja2** [comment]
I opted for this slightly newer more modern one:
https://www.nexusmods.com/skyrimspecialedition/mods/45253

**Comment by Trevail** [comment]
I like the newer one as well, felt Know Your Enemy was a little to limiting for certain builds while this one seems a little more lenient while still giving some added difficulty.
