### ISSUE TITLE
micmou's List of shit for Guitar to update.

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#300]
Skyrim's Paraglider 1.0 > 1.5
Radiant Requirment MCM 1.1 > 1.2
Antiquary - Enhanced Artifacts 1.2.2 > 1.3.2
Wyrmstooth 1.19.7 > 1.19.8
Undeath 3.45 > 3.55
SSE Display Tweaks 0.5b > 0.5.9
Papyrus Util SE 3.9 > 4.3
Scaleform Translation Plus Plus 1.4.1 > 1.5.0
ConsoleUtilSSE 1.2 > 1.3.2
Unofficial Skyrim Creation Club Content Patches 6.1 > 6.4

**Comment by micmou** [comment]
Actor Limit Fix 2 > 5
SSE Engine Fixes (skse64 plugin) 5.8 > 6.0.2
Bug Fixes SSE 3.0 > 6.0
Equip Enchantment Fix 1.3.2 > 1.3.4
powerofthree's Papyrus Extender (Versioning is fucked) > 12 Jan 2022
Base Object Swapper 1.1 > 1.2
Better Third Person Selection - BTPS 0.3.2 > 0.3.3
Assorted mesh fixes 0.41 > 0.45.1
Fixed Mesh Lighting 1.4.2 > 1.7.1
Whiterun Mesh Fixes 1.1.5 > 1.2.5
Happy Little Trees (Versioning Fucked) > 1.02 Beta 3
Simplicity of Snow 0.5 > 0.5.1
Mari's flora 1.1 > 1.2
Underground - a dungeon texture overhaul 1.0 > 1.2
Spice of Life - Orc Strongholds SE 1.0 > 1.2
Ruins Clutter Improved 3.2 > 3.2b
Rudy HQ - Miscellaneous SE 1.0.1 > 1.0.2
JS Purses and Septims SE 1.1 > 1.2
Modular Armory - Community Collection 1.0 > 1.2
Particle Lights For ENB SE - Undead Creatures 1.0 > 1.1
Pilgrim - A Religion Overhaul 1.0.12 > 1.0.12.1
Survival Mode Improved (Fucked Versioning) > 1.2.7
Follower Trap Safety 1.3 > 1.4
Optional Quick Start - SE 1.0.2 > 1.0.3
Stackable Stones of Barenziah with Optional Quest Markers 1.0 > 2.0
A Place To Rest Their Heads SSE - Tweaked 1.0 > 1.0.1
Immersive Equipment Displays 1.2.3 > 1.3.2
Majestic Bruma Mountains 1.0 > 1.1
VIGILANT and GLENMORIL - Book Covers 1.2 > 1.3

**Comment by micmou** [comment]
The Lost Wonders of Mzark 1.7 > 1.8 (Fix the versioning you goober)
Additional Clockwork 2.0 > 2.0.2
Lucien - Anniversary Edition - All-In-One Creation Club Patch 1.6.2 > 1.6.3
Bogmort - Mud Monsters of Morthal Swamp 1.0 > 2.0
Legacy of the Dragonborn SSE 5.5.7 > 5.6.0
Legacy of the Dragonborn - Creation Club Patch Hub 5.1.2 > 5.1.3
Legacy of The Dragonborn - Museum Exterior Fixes 0.3.2 > 0.4
Creation Club Integration - Armours 3.0 > 3.0.3
Morrowind Threads - A Creation Club Integration Mod 1.1.1 > 1.1.2
Goblins - Spears Addon and Bruma Patch 2.0 > 2.2.0
Ghosts of the Tribunal - Solstheim Integration 1.0 > 1.1
Simple Dual Sheath 1.5.1 > 1.5.2
Dynamic Animation Replacer 1.1 > 1.1.2
Animation Motion Revolution 1.4 > 1.5
Pause After Load Unscripted 1.0.0.7 > 1.0.0.9
Simple Load Screens 1.2 > 1.5.4
eFPS - Official Patch Hub 1.5 > 1.6

**Comment by Guitarninja2** [comment]
Done!
