### ISSUE TITLE
Banoliers and pouches with vials are missing textures

### ISSUE THREAD

**Issue by jawebb87** [Guitarninja2/septimus#306]
![enb2022_3_14_02_59_01](https://user-images.githubusercontent.com/61367045/158130310-2ba62d46-02c6-47b2-8470-3c432cb73ead.jpg)
![enb2022_3_14_02_59_45](https://user-images.githubusercontent.com/61367045/158130359-6c1cb499-e705-42b1-8989-2d4ddaccfa0f.jpg)

**Comment by Guitarninja2** [comment]
Fixed in beta3
