### ISSUE TITLE
Adamant + Tinkers Forge compat

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#308]
Need compat with adamant an tinkers forge because with 110 smithing and shitting a dragon soul into the whetstone we only get up to decent or good.
https://i.imgur.com/W00MtNp.jpg
https://i.imgur.com/qJrUTyt.jpg

**Comment by micmou** [comment]
Figured I would attach this
Its a console bat that levels all your skills up to 100 using incpcs

**Comment by micmou** [comment]
[skills.txt](https://github.com/Guitarninja2/septimus/files/8251004/skills.txt)

**Comment by Guitarninja2** [comment]
This is now fully fixed for beta 3. I did a complete overhaul of that tree myself.
