### ISSUE TITLE
Sugestion: Complete documentation with widescreen guide

### ISSUE THREAD

**Issue by Zriel88** [Guitarninja2/septimus#31]
Apart from linking to TPF widescreen guide, it would be nice to mention if any extra addon is needed.
I think we need "SkyUI - Survival Mode Integration - Widescreen Fix" and "Creation Club - Widescreen Fix" for the CC profile.

**Comment by Guitarninja2** [comment]
Ah yeah a widescreen section would be a good idea. I may just throw that into the mod list directly as an optional mod.

**Comment by Guitarninja2** [comment]
This one should be good to go in 1.7.0-BETA5
