### ISSUE TITLE
LoTD Book Covers Skyrim

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#312]
Book covers should be disabled if people have LOTD enabled
A minor thing but it can't hurt to have a extra instruction for LoTD folks.

**Comment by micmou** [comment]
Book Covers is included by default in LoTD

**Comment by micmou** [comment]
Ohh also the Moon and star immersion patch should not be used the LoTD patch does it already NTM the MAS immersion patch breaks shit

**Comment by Guitarninja2** [comment]
I will remove the MAS immersion patch. Book covers is fine. It'll just overwrite some stuff but they are the same.
