### ISSUE TITLE
LOTD patches

### ISSUE THREAD

**Issue by x-Slim** [Guitarninja2/septimus#317]
More disabling LOTD shenanigans

![image](https://user-images.githubusercontent.com/64661148/158930788-fee6ed47-12b9-4f60-a608-8bd6f7b2fb7b.png)

Septimus - Patches has an extra LOTD patch packaged in it

Alternate Start - A New Dragonborn Expansion also has a LOTD patch in it

**Comment by Guitarninja2** [comment]
This should be fixed now. Uploaded a fixed beta 3 :D
