### ISSUE TITLE
Unknown Variables in Autorun

### ISSUE THREAD

**Issue by x-Slim** [Guitarninja2/septimus#318]
Noticed these in the console on a new save

![image](https://user-images.githubusercontent.com/64661148/158932626-6898220c-5df5-4a4f-b9cf-a47ef1f2ec70.png)

**Comment by Guitarninja2** [comment]
Interesting. They might be super old autorun commands from LOTF.

**Comment by Guitarninja2** [comment]
Fixed thanks!
