### ISSUE TITLE
"Akatosh's Chosen" Dragonborn Start has Continuity Errors - locked out of Whiterun

### ISSUE THREAD

**Issue by phinocio** [Guitarninja2/septimus#319]
Version: Beta 3 "Septimus - Anniversary Edition" profile.

Optional mods enabled:

- Time Format Changer
- Quick Loot RE (default enabled on install)
- SkyHUD - White Dot Crosshair
- Night Eye ENB Fix (default enabled on install)
- Perks for NPCs (EEOS + Others)
- Fast Travel for Survival Mode (default enabled on install)

Upon choosing the Dragonborn start you start at High Hrothgar with the quest to go talk to Delphine in the Riverwood Inn. 

Upon doing so I started the quest to kill a Dragon in Kynesgrove. Decided to stop at Whiterun on the way...to find out I am locked out of the city, with only 2 guard dialog options

- Intimidate check

- I'll come back later.

Leaving me locked out of the city - which is a major continuity error as to get to the point in the main quest I am at - I'd have to have visited the city before. (Iirc I'm also thane at this point of the quest which is hilarious that the thane is locked out haha). 

Another possible continuity error I need to check on (so speculating here), is the Golden Claw quest. Should I start it and go retrieve the claw, I will need to cut down Arvel and kill him. However to get to the point I am at in the main quest currently, it would be implied I got past him somehow...and then he got trapped in the web again. 

Update: I can confirm my character is a psychopath and left Arvel to be trapped again.

I also just realized that also implies the character got past the puzzle gate without the Golden Claw

**Comment by Guitarninja2** [comment]
Yeeted that start for now. Sounds like it has some problems.
