### ISSUE TITLE
Mod suggestion: Another Archery Patcher / (AGO) 

### ISSUE THREAD

**Issue by Omrga** [Guitarninja2/septimus#32]
I noticed, if I'm not mistaken, there is no archery gameplay change so I suggest Another Archery Patcher. 

For the archery lovers among us. 
It should be pretty light and compatible. 

https://www.nexusmods.com/skyrimspecialedition/mods/53810

Maybe Archery Gameplay Overhaul can be added as well, but I'd suggest using the physics from Another Archery Patcher. 

https://www.nexusmods.com/skyrimspecialedition/mods/24296

Edit: Didn't realize Synthesis is a tool lol

**Comment by Guitarninja2** [comment]
Some sort of archery changes would be good yeah. I'll look into these and some alternatives. I agree laser bows aren't particularly fun.
