### ISSUE TITLE
Graphical Issues

### ISSUE THREAD

**Issue by AAveros** [Guitarninja2/septimus#324]
Odd blurry textures for silver plates; found them on Dragonsreach Balcony
![image_2022-03-18_144955](https://user-images.githubusercontent.com/101903452/159081245-6193ba17-879b-44c0-b274-3000273a4267.png)

**Comment by AAveros** [comment]
Brazier rock textures outside the Palace of Kings (Windhelm) seem very low res
![enb2022_3_18_23_51_45](https://user-images.githubusercontent.com/101903452/159109178-f0b8d2ba-48dd-4bbb-9597-ee85709e34d4.jpg)

**Comment by Guitarninja2** [comment]
This should be good now. I believe the fire in windhelm is just a not amazing texture.
