### ISSUE TITLE
Mannequins moving oh my

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#326]
Uhh oh skoobs looks like the list author didnt include the mannequin slapper patch for DBM that the author provided.
https://cdn.discordapp.com/attachments/950113338841530430/954542441992704020/SkyrimSE_0s30KxjEP4.jpg

Well zoinks shaggy 

in all seriousness easy fix Icecreamassissin the one who made LoTD and your choice of mannequin managment tool also provides a version for lotd on the Mannequin Managment mod page.

**Comment by Guitarninja2** [comment]
done
