### ISSUE TITLE
Cobweb lighting issue

### ISSUE THREAD

**Issue by GunnZeug** [Guitarninja2/septimus#327]
Lighting is cast on Arvel's cobwebs differently in bleak falls barrow depending on the angle you look at them at, both with and without an ENB enabled

https://user-images.githubusercontent.com/101950838/159138070-e8b19837-fc86-4e8d-a97e-55b4fb3888ac.mp4

.

**Comment by Guitarninja2** [comment]
This should be sorted out for beta 4. Thanks for the report!
