### ISSUE TITLE
Malur Seloth, Steward of Winterhold, refuses to sell the key to Hiberna Lodge

### ISSUE THREAD

**Issue by Arkspawn** [Guitarninja2/septimus#328]
The dialogue goes through "I'll take it!" and then he says "Splendid, here is the key to your new home", but doesnt take 4000 gold and doesnt give me the key. The dialogue is then repeatable.

**Comment by Guitarninja2** [comment]
This is unfortunately a bug with the mod that can't be fixed :( We've removed it in the newest version
