### ISSUE TITLE
Double Static Items - Windhelm, near Refugees Rest

### ISSUE THREAD

**Issue by JunosJael** [Guitarninja2/septimus#329]
On the shrines to Boethiah, Mephala and Azura, all the items seem to be duplicated. Iron Sword x 2, Hide Shield x 2, Book x 2, Gold Ingot x 2. Not sure about the gold or flowers, but on the others, there's two of each perfectly on top of each other.

Graveyard next to Refugees Rest in Windhelm when starting the game as Mercenary from Northern Morrowind.

**Comment by Guitarninja2** [comment]
Fixed
