### ISSUE TITLE
Bug: Convenient Dialogue UI - SE

### ISSUE THREAD

**Issue by Zriel88** [Guitarninja2/septimus#33]
https://www.nexusmods.com/skyrimspecialedition/mods/57943
Mod doesnt work on Septimus 1.7.0 beta. I think it wasn't working on 1.6.6 neither altough I was also using ultrawide patches that may interfere.
It is being overwritten "Better dialogue controls". I think it is redundant.
![Dialogue](https://user-images.githubusercontent.com/8926895/143573581-380a8ca8-391a-480e-9279-3413e6616fa1.png)

**Comment by Guitarninja2** [comment]
Yuuppp. Looks like it was being written by better dialogue controls. Good catch!

**Comment by Guitarninja2** [comment]
Fixed in 1.7.0-beta4
