### ISSUE TITLE
Mod suggestion: Apocalypse - Ocato's Recital - Auto Dispel

### ISSUE THREAD

**Issue by screwyprof** [Guitarninja2/septimus#330]
**TLDR;** Spells cast through Ocato's Recital get automatically dispelled at the end of the fight.

https://www.nexusmods.com/skyrimspecialedition/mods/19413

**Comment by micmou** [comment]
Thought the balance patch we had already did this?

**Comment by Guitarninja2** [comment]
Done for beta 4. Balance patch is in too.
