### ISSUE TITLE
Trainfight ending conflict

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#334]
When I finished Trainfight (extremely fun!) and took the elevator up, I ended slightly underneath the ground in the vicinity of the dwarven elevator tower where the elevator shaft should currently exit on the surface. As I said, instead of putting me inside this elevator tower it put me underground nearby I jumped around a bit and was able to get above ground somehow. 

Attached is a screenshot of the dwarven elevator tower
![Skyrim Special Edition 3_20_2022 3_07_30 PM](https://user-images.githubusercontent.com/508163/159178600-3e075f98-5d6f-44a4-85e2-63406da26515.png)
.

**Comment by Guitarninja2** [comment]
Oh that's really strange lol. I'll see what I can do.

**Comment by rsrogers4** [comment]
Not super high priority. At least it counts as outside so people can fast travel to a normal location. And it’s after the quest is finished.
________________________________

**Comment by Guitarninja2** [comment]
@rsrogers4 Is this still an issue?

**Comment by rsrogers4** [comment]
The same issue was present in 3.0.2.2. You are supposed to come out of an dwarven elevator near Solitude, but instead you come out slightly underneath the ground (a think layer of snow is above you). If you jump, you can get on top of the snow... so not a huge deal.

**Comment by Guitarninja2** [comment]
Interesting lol. It might be a problem with the mod itself then.
