### ISSUE TITLE
Blocky Fire Effect

### ISSUE THREAD

**Issue by Curly0208** [Guitarninja2/septimus#338]
As per your request Guitar, here you go. Weird fire effect for the LOTD alternate start. 

https://cdn.discordapp.com/attachments/950115234876645407/956311798364135444/The_Elder_Scrolls_V_Skyrim_Special_Edition_Screenshot_2022.03.23_-_18.00.56.72.png

https://discord.com/channels/773659452392865792/950115234876645407/956311866710323250

**Comment by Guitarninja2** [comment]
Fixed!
