### ISSUE TITLE
Capitals and Towns of Skyrim issues

### ISSUE THREAD

**Issue by AAveros** [Guitarninja2/septimus#339]
Dawnstar carriage driver is inside the wall
https://discord.com/channels/773659452392865792/950113338841530430/956401146451341384

Some of Dawnstar's wall segments are missing and are instead invisible barriers
https://discord.com/channels/773659452392865792/950113338841530430/956401433228501002

Landscape seam in front of Morthal
https://discord.com/channels/773659452392865792/950113338841530430/956401615810752523

**Comment by Guitarninja2** [comment]
Fixed!
