### ISSUE TITLE
Bug: Complete widescreen fixes conflicts with "Convenient Dialogue"

### ISSUE THREAD

**Issue by Zriel88** [Guitarninja2/septimus#35]
interface\dialoguemenu.swf conflicts with "Convenient Dialogue" and thus it doesn't load.
In any case I don't think a fix for UW is needed for "Convenient Dialogue". Attached a screen with the conflicted file hidden. Don't think it is weird at all on UW resolution,
![Captura](https://user-images.githubusercontent.com/8926895/143676844-f41cdd94-1c83-41cf-8460-d38e2b021cda.PNG)

**Comment by Guitarninja2** [comment]
yep. I'll just remove that file in the widescreen fixes mod. It isn't really necessary.

**Comment by Guitarninja2** [comment]
Fixed for 1.7.0
