### ISSUE TITLE
Beta 5: Haunting Curse (conjuration perk) can't be "bought"

### ISSUE THREAD

**Issue by PedroC47** [Guitarninja2/septimus#351]
I tried reloading a save and making the skill legendary and it doesn't work
edit: adding the perk through console commands works (tested on a wispmother only, should work with every enemy), but results in a gray perk text
![beta 5 issue](https://user-images.githubusercontent.com/22136507/160293907-581f0d1b-45d2-40b8-9343-d76d4551103a.png)
![Skyrim Special Edition 27_03_2022 18_59_07](https://user-images.githubusercontent.com/22136507/160294392-7edcc770-bf6c-44c9-91fe-a10bc23a0219.png)

**Comment by Guitarninja2** [comment]
Fixed. It was a problem with the new adamant update
