### ISSUE TITLE
Septimus 3 - Beta 5 27.3.2022

### ISSUE THREAD

**Issue by TrinomisBirdy** [Guitarninja2/septimus#352]
Bug: 
Fortify Stamina Enchantment is available twice as a known Enchantment.
One was gained by disenchanting the "Ring of Minor Stamina", the other from "Back Left - Leather Vial Holder"
The Same works for "Back Left - Dark Book Holder" and any other Fortify Magicka Enchantment.

**Comment by Guitarninja2** [comment]
Fixed for the final release!
