### ISSUE TITLE
Community overlays (tattoos and face paint) for males are missing.

### ISSUE THREAD

**Issue by dreyo69** [Guitarninja2/septimus#360]
![Screenshot (653)](https://user-images.githubusercontent.com/102598354/160613321-11e6a474-01b6-4f83-a847-0db70a3387e9.png)

**Comment by Scarlet-Stinger** [comment]
quick check on this, we only have the female unp paints installed.
the female paints stretch weird on male characters. 

https://www.nexusmods.com/skyrimspecialedition/mods/22487?tab=files
no file is specified as male or female, we have (1) which is unp 2k body

https://www.nexusmods.com/skyrimspecialedition/mods/26224?tab=files
we have (1) which is female unp , could get (3) which is male / female 
adds ~74mb to install

https://www.nexusmods.com/skyrimspecialedition/mods/35339
we have (1) which is female unp, could get (3) which is male / female

**Comment by dreyo69** [comment]
yeap the links you sent have the male versions

**Comment by Guitarninja2** [comment]
Fixed now
