### ISSUE TITLE
Overlapping barrels in Old Hroldan (Septimus 3.0.0)

### ISSUE THREAD

**Issue by Zwikkry** [Guitarninja2/septimus#365]
Septimus version. 3.0.0
Location: Old Hroldan
Player pos: -114934 -8625
Barrel pos; -115043.81 -8686.19

There are some overlapping barrels next to Vilar's House in Old Hroldan (see img and mp4)

![barrel](https://user-images.githubusercontent.com/32293196/160709089-0c8949d8-8d40-4763-9787-29c3f2eaf2df.png)

https://user-images.githubusercontent.com/32293196/160709145-1d0944f7-ae21-4c9f-9451-e8d15324318b.mp4

**Comment by Guitarninja2** [comment]
Fixed in 3.0.3
