### ISSUE TITLE
Duplicate new NPCs in Old Hroldan (3.0.0)

### ISSUE THREAD

**Issue by 4ulender** [Guitarninja2/septimus#367]
Noticed that the new NPCs at Old Hroldan are duplicated. They also have a tendency to stand on top of each other.
![20220329224936_1](https://user-images.githubusercontent.com/96638017/160741297-b1420031-6821-47a7-a123-7197b49bf07f.jpg)
![20220329224816_1](https://user-images.githubusercontent.com/96638017/160741309-0d75ca04-c823-44d2-8837-22ac56cff1c5.jpg)

**Comment by Zwikkry** [comment]
Considering my issue #365 , maybe the whole house has been duplicated instead of just the barrel and NPC

**Comment by LoD7995** [comment]
Can confirm that.

**Comment by LoD7995** [comment]
Reason for that is most likely that "Village of Old Hroldan" is already included in "Capitals and Towns of Skyrim" and thus duplicated.

**Comment by Guitarninja2** [comment]
Thank you. Yeah that's probably why.

**Comment by Guitarninja2** [comment]
Fixed in 3.0.3
