### ISSUE TITLE
LotD store supplies

### ISSUE THREAD

**Issue by Ashensakar** [Guitarninja2/septimus#369]
LoTD store supplies gave me a huge -1000000 carry weight
![20220330224037_1](https://user-images.githubusercontent.com/68168803/160935773-6d831062-3acd-46e4-9e68-a630df444251.jpg)

**Comment by Guitarninja2** [comment]
This might be an LOTD bug actually.

**Comment by Ashensakar** [comment]
Storing the potions before using "store supplies" and the carry weight bug didn't happen, soo its something with the potions and LoTD storing.
