### ISSUE TITLE
EVG rain animation bug

### ISSUE THREAD

**Issue by rheabutt** [Guitarninja2/septimus#37]
with the shield being on the players back the animation where the player holds their shield up when it's raining just becomes this
![New Bitmap image](https://user-images.githubusercontent.com/44508315/143795258-8078c4bd-7d3c-42d9-8b11-e919a09c3128.png)

**Comment by Guitarninja2** [comment]
Lol good catch. I may just remove the shield on back honestly. What's your opinion on that?

**Comment by rheabutt** [comment]
Dislike it for clipping tbh, capes and backpacks are already hard enough to get looking right lol

**Comment by Guitarninja2** [comment]
Yup agreed. Going to ditch it in 1.7.6

**Comment by Guitarninja2** [comment]
Done in 1.7.6
