### ISSUE TITLE
Katana + Shield Animations broken after updating from 3.0.0 to 3.0.2.2

### ISSUE THREAD

**Issue by DudeGrim** [Guitarninja2/septimus#379]
This is the Katana + Shield animation in 3.0.0
![20220402214323_1](https://user-images.githubusercontent.com/9623863/161386215-da8f8593-d2b1-48c8-aeeb-37eef34a3162.jpg)

<hr>

Here it is in the 3.0.2.2
![20220402215637_1](https://user-images.githubusercontent.com/9623863/161386629-2de4d1ff-41ed-4be9-94a9-fd79c45f3014.jpg)

Both is from the same save file (if that makes a difference tell me), fresh Septimus install, and no usage of optional mods. Profile is just the "Septimus" profile (not AE). Seeing other people in the discord bugs and questions having problems with FNIS? Maybe related or not IDK might be useful. Tell me if I need to add more info.

**Comment by Guitarninja2** [comment]
Should be fine now in 3.0.4
