### ISSUE TITLE
BSBruma majestic mountains conflict

### ISSUE THREAD

**Issue by rheabutt** [Guitarninja2/septimus#38]
![20211129001950_1](https://user-images.githubusercontent.com/44508315/143819787-00a0dacc-2bed-4544-8532-23ed6fa779e8.jpg)
Conflict on some rock meshes with majestic mountains in bruma

**Comment by rheabutt** [comment]
https://www.nexusmods.com/skyrimspecialedition/mods/53152?tab=files found this patch, may be out of date but still might be useful for finding a fix

**Comment by Guitarninja2** [comment]
Cool yeah I'll take a look. Thanks!

**Comment by Guitarninja2** [comment]
Should be fixed in 1.8.0
