### ISSUE TITLE
Silverware wrong UVs

### ISSUE THREAD

**Issue by LoD7995** [Guitarninja2/septimus#381]
![Screenshots19](https://user-images.githubusercontent.com/83468628/161387485-12d1e151-5dd6-4a3b-9f3e-c8a331dbabb4.png)

Rudy's Silverware should be given priority over RCI and High Poly Project.

**Comment by Guitarninja2** [comment]
Thank you

**Comment by Guitarninja2** [comment]
Fixed in 3.0.3
