### ISSUE TITLE
Torch transparency issue with ENB

### ISSUE THREAD

**Issue by LoD7995** [Guitarninja2/septimus#382]
![ScreenShot22](https://user-images.githubusercontent.com/83468628/161388094-c19c63e8-8659-4eaf-96af-c9437e023225.png)

**Comment by Guitarninja2** [comment]
Cannot reproduce this myself

**Comment by LoD7995** [comment]
To reproduce:
player.additem 1d4ec 1 via console
And you can turn up the brightness of the ENB to make it more obvious.
