### ISSUE TITLE
Guitars TODO list

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#383]
Update Adamant, Thaumaturgy, Mysticism
~~Fix Sun spells not being able to damage non undead with auriels~~ Moved to own issue.
Nordic UI compass Markers Restored
Update LOTD Patches

**Comment by micmou** [comment]
@Guitarninja2 Swiggityswoggity

**Comment by Webmetz** [comment]
Maybe separate these into separate issues?

In regards to Sun Damage
> Pilgrim is not updated to fully support Mysticism 2 rn

![image](https://user-images.githubusercontent.com/2394842/161391238-bc2d6e74-ccbb-484f-a44c-03a1ee7cc2e9.png)

There is some Myst2 Conflicts.

**Comment by micmou** [comment]
Update LOTD Patches

**Comment by micmou** [comment]
Ill ask this here so it doesnt get lost @Guitarninja2 . The two things you edited out of the list the uncapper preset and the yeeting of ancient nordic armory. Does you editing them out mean that you have done them or are not going to do them. Because on both of those you asked me to remind you.

**Comment by Guitarninja2** [comment]
Done for 3.0.3
