### ISSUE TITLE
Sunspells not getting auriels beautiful love

### ISSUE THREAD

**Issue by micmou** [Guitarninja2/septimus#384]
Maybe separate these into separate issues?

In regards to Sun Damage
> Pilgrim is not updated to fully support Mysticism 2 rn

![image](https://user-images.githubusercontent.com/2394842/161391238-bc2d6e74-ccbb-484f-a44c-03a1ee7cc2e9.png)

There is some Myst2 Conflicts.

_Originally posted by @Webmetz in https://github.com/Guitarninja2/septimus/issues/383#issuecomment-1086668315_

**Comment by micmou** [comment]
There ya go @Webmetz

**Comment by Guitarninja2** [comment]
Fixed in 3.0.4
