### ISSUE TITLE
Quest mod Requests

### ISSUE THREAD

**Issue by DomRe** [Guitarninja2/septimus#388]
Hi, was wondering if these mod requests could please be considered?

[The Wheels of Lull - Unwound Edition](https://www.nexusmods.com/skyrimspecialedition/mods/748/)

[Here there be Monsters SSE](https://www.nexusmods.com/skyrimspecialedition/mods/35929)

[Here There Be Monsters - The Call Of Cthulhu SSE](https://www.nexusmods.com/skyrimspecialedition/mods/35934)

[Here There Be Monsters - Sign of Cipactli SSE](https://www.nexusmods.com/skyrimspecialedition/mods/35933)

[The Cheese of Ages](https://www.nexusmods.com/skyrimspecialedition/mods/27465)

[Caught Red Handed - Quest Expansion](https://www.nexusmods.com/skyrimspecialedition/mods/65708)

[Winterhold Deep-Sea Ruins](https://www.nexusmods.com/skyrimspecialedition/mods/53707)

[Underwater Treasure SSE](https://www.nexusmods.com/skyrimspecialedition/mods/17267)

[Beyond Reach](https://www.nexusmods.com/skyrimspecialedition/mods/3008)

[Carved Brink](https://www.nexusmods.com/skyrimspecialedition/mods/24351)

They are mostly quest mods I think would really help to add some fresh content to a modded skyrim playthrough, especially since I don't see them added often, additionally, many have LOTD patches to support them.

**Comment by Guitarninja2** [comment]
Many of these were originally in the list but had to be removed for stability reasons.
