### ISSUE TITLE
Plant clipping with crates in Whiterun

### ISSUE THREAD

**Issue by SnellieSnale** [Guitarninja2/septimus#389]
Very small thing I noticed. In Whiterun there is a plant clipping with some crates.

![Screenshot_6](https://user-images.githubusercontent.com/77302181/161425054-98360344-6501-4b69-ac02-6e9619eb01fc.jpg)
![Screenshot_7](https://user-images.githubusercontent.com/77302181/161425057-cc4f37a3-1dbc-4cc0-9897-6d31c8c812a6.jpg)

**Comment by Guitarninja2** [comment]
Fixed in 3.0.3
