### ISSUE TITLE
New patch for MM Bruma

### ISSUE THREAD

**Issue by rheabutt** [Guitarninja2/septimus#39]
https://www.nexusmods.com/skyrimspecialedition/mods/59265/?tab=description

Old bruma patch was outdated and only covered a couple of specific meshes, made a new one here

**Comment by Guitarninja2** [comment]
Oh awesome okay. I just need this patch and not the old one right?

**Comment by rheabutt** [comment]
Yeah, thanks for all the work on the list!

**Comment by Guitarninja2** [comment]
Thank you! I'll throw that one in.

**Comment by rheabutt** [comment]
on second thought may have some issues, might want to load both until I can figure out and update

**Comment by Guitarninja2** [comment]
Sure yeah. I'll load the original one and can sort out the rest when you're all good.

**Comment by rheabutt** [comment]
Alright should be good to do on it's own

**Comment by Guitarninja2** [comment]
Added this one in for 1.8.2. Thanks again!
