### ISSUE TITLE
Coffee tankard restores 5 health for 0 seconds

### ISSUE THREAD

**Issue by SnellieSnale** [Guitarninja2/septimus#391]
Not sure if this is actually an issue, but it seems... not right.
![Screenshot_9](https://user-images.githubusercontent.com/77302181/161425177-e97e185f-b9d2-4bdb-a762-2c77e5e509f0.jpg)

**Comment by Guitarninja2** [comment]
Yeah that needs another look heh.

**Comment by Guitarninja2** [comment]
Fixed in 3.0.3
