### ISSUE TITLE
Quickloot issue in regards to stealing items

### ISSUE THREAD

**Issue by SnellieSnale** [Guitarninja2/septimus#392]
I noticed that when a container contains items that you are allowed to take and are not allowed to take (stealing), that all items show up as 'allowed to take' in the quickloot menu. When opening the container it displays correctly. In the screenshots below, I have actually already taken some gold out the container which I was allowed to take.

![Screenshot_4](https://user-images.githubusercontent.com/77302181/161425328-d356a488-f3cc-4fc2-a38f-b64fe7d84dff.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/77302181/161425329-b3027384-6e16-4d61-9439-9dafa4a2ed21.jpg)

**Comment by SnellieSnale** [comment]
Appears to be an issue with Quick loot RE: https://github.com/Ryan-rsm-McKenzie/QuickLootRE/issues/109

**Comment by Guitarninja2** [comment]
I'm gonna file this under known issues for quickloot. I don't think it's ever getting fixed :(
