### ISSUE TITLE
The forgemaster's fingers replica is available to smith

### ISSUE THREAD

**Issue by SnellieSnale** [Guitarninja2/septimus#394]
The forgemaster's fingers LOTD replica is available to smith at every forge. I haven't even encountered the original ones.

![Screenshot_4](https://user-images.githubusercontent.com/77302181/161481371-8fdeea13-f6bb-4e28-b00c-97248a741126.jpg)

**Comment by Webmetz** [comment]
That isn't a bug.  That is what is unlocked when you become a Blood Kin of orcs, which prevents you from getting the quest for the fingers.
