### ISSUE TITLE
Jade from Interesting NPCs

### ISSUE THREAD

**Issue by believeinyuna** [Guitarninja2/septimus#396]
the requirement to recruit jade from interesting npcs in the mod added for it is have mara's blessing. i just got mara's blessing from a priest of mara and tried to get her to follow me, i selected the dialogue for it but she's not following me, and the dialogue option is gone now. i tried going to the temple itself and interacting with a shrine of mara then going back, but still no dialogue option to ask her to follow. version 3.0.2.2, a fresh save on this version.

**Comment by Guitarninja2** [comment]
Removed the follower requirements mod in 3.1.0
