### ISSUE TITLE
Upgraded Crossbows disappearing after being dropped

### ISSUE THREAD

**Issue by Dog780** [Guitarninja2/septimus#397]
I've only tested with +4 Iron and Steel crossbows but they've disappeared every time I've dropped them or been disarmed with them in my hands, I thought they might've just been put to somewhere else in the cell but looked around a lot and did not seems them anymore. I did not have this issue with the other upgraded items in my inventory, my Silver Shortsword +5 and my Relic Hunter and Skaal gear +4 did not disappear.

**Comment by Guitarninja2** [comment]
Is this on the AE profile or normal profile?
