### ISSUE TITLE
Mod-added bound weapons not working with perks

### ISSUE THREAD

**Issue by PessimisticMango** [Guitarninja2/septimus#399]
My bound quarterstaff isn't absorbing health/magicka/stamina after getting the Essence Drain perk, nor does it last longer from Arcane Weapon. The bound bow works as intended. I've not tested with other weapons.
I'm not sure if this also affects the other bound weapon perks (probably).

This is on the normal (not AE) profile, version 3.0.3.1

**Comment by Guitarninja2** [comment]
Ah yes. They need the proper keywords for mysticism. Thank you. I'll get this sorted out for 3.0.4

**Comment by Guitarninja2** [comment]
This should be fixed in the next update
