### ISSUE TITLE
Quick Light MCM menu won't open

### ISSUE THREAD

**Issue by Calcyon85** [Guitarninja2/septimus#40]
The Quick Light MCM menu still shows in the menu but when I click on it, it won't open. I was hoping to play around with the brightness setting.

**Comment by Guitarninja2** [comment]
Hmm that's really strange yeah. I'll take a look.

**Comment by Guitarninja2** [comment]
It seems to open fine for me. Do the tabs on the left not show up? It doesn't open the first menu by default for some reason so I have to click that manually first.

**Comment by Calcyon85** [comment]
Sorry, boss. Seems it was a false alarm, I restarted Skyrim several times, but for some reason this last time fixed it. Thanks and sorry again for wasting your time!

**Comment by Guitarninja2** [comment]
No worries!
