### ISSUE TITLE
Not all bags are balanced yet

### ISSUE THREAD

**Issue by thbolijn** [Guitarninja2/septimus#400]
Some bags haven't been included in the balance patch introduced in 3.0.3
![image](https://user-images.githubusercontent.com/50100271/162026932-b2152861-59d5-43eb-a2ec-c028c046d11e.png)
![image](https://user-images.githubusercontent.com/50100271/162026962-ff1eda60-9291-4e1a-b9d2-271a71aa1ee7.png)

Something to keep in mind
![image](https://user-images.githubusercontent.com/50100271/162030096-4136e823-7f97-4e84-9b84-7e5f62dc45f5.png)

**Comment by Guitarninja2** [comment]
This should be fixed in 3.1.0
