### ISSUE TITLE
The perk "Treasure Hunter" from the security tree is only working with normal chests.

### ISSUE THREAD

**Issue by AlleinKrieger** [Guitarninja2/septimus#401]
It was supposed to give a chance to appear golden platter, goblet, bowl etc in any chest, but it only works with the normal chests you find around skyrim and in draugr dungeons.

**Comment by Durgenage** [comment]
What exactly is the issue? Are you classifying every dresser and urn as a 'chest' or something? I took the perk and ran Bleak Falls Barrow and found 8 golden items. 1500 * 8 = 12000 gold for one dungeon. There were usually multiple items in one chest. If anything it is overtuned.

**Comment by Guitarninja2** [comment]
I think the concern is with like falmer chests etc. Might be worth checking them.

**Comment by Guitarninja2** [comment]
Nothing is overwriting this perk so I have to assume this is intended with adamant.
