### ISSUE TITLE
High-level enemy spawning in Bleak Falls Barrow as a level 3

### ISSUE THREAD

**Issue by dlynge** [Guitarninja2/septimus#404]
As a level 3 I encountered a level 14 troll at the small bridge/chasm in bleak falls barrow. The troll was incredibly difficult to kill even after lowering the difficulty. 

![image](https://user-images.githubusercontent.com/39055193/162111536-6d2058db-e679-4c90-88c9-0cf562a82852.png)

**Comment by SnellieSnale** [comment]
I found it very easy (level 4) with the fire ball scroll you can find earlier in the dungeon. I am using the optional content,  Blade and Blunt - Realistic Damage, so that might be the reason why it was way easier :)

**Comment by Webmetz** [comment]
That would be fixed with the latest BUVARP Patch
https://www.nexusmods.com/skyrimspecialedition/mods/56120
> Thomas Encounter in Bleak Falls Barrow: Added a low level variation called Wounded Troll, which should be easier to kill for low level characters.

**Comment by Guitarninja2** [comment]
Fixed in 3.0.4
