### ISSUE TITLE
Lockpick Trainers Train Hand to Hand

### ISSUE THREAD

**Issue by nanatheold** [Guitarninja2/septimus#407]
These are the two I have found so far. Vex in Thieves Guild and Mahad in Khajit caravan outside Solitude
![vex2](https://user-images.githubusercontent.com/103223111/162328698-5b35a862-bc71-410f-8c8f-bfc60476f4b3.jpg)
![mahad](https://user-images.githubusercontent.com/103223111/162328705-ef302c75-fcd6-4660-917d-87a6cd956d25.jpg)
![vex](https://user-images.githubusercontent.com/103223111/162328713-00f28289-36dc-4b84-988f-86f4a675918a.jpg)
![mahhad2](https://user-images.githubusercontent.com/103223111/162328719-5ee5447d-f0ee-4d02-84fb-39edf94839fe.jpg)
.

**Comment by Xgatt** [comment]
This isn't really a bug, and more of a dialogue edit needed. Hand to Hand mod does say that all Lockpicking trainers will train you in hand to hand now.

**Comment by Guitarninja2** [comment]
Yeah it basically comes down to whether or not we want them to be hand to hand. We can always switch them to pickpocket (security) if we want.

**Comment by Xgatt** [comment]
One thing though is H2H claims Vex is no longer a trainer, but she clearly seems to be one here. Will check it out

**Comment by nanatheold** [comment]
I was just reporting. I understand my preferred build is no longer 'in fashion' but old ladies with poor reflexes can still be successful with sneak thief archers. Lol. I am fine training my skills the old-fashioned way.

**Comment by Xgatt** [comment]
You can just go to a former Pickpocket trainer, and they should be able to train you in security. No need to give up the build or struggle with it.

**Comment by Guitarninja2** [comment]
For now this is "normal". we may adjust in the future.
