### ISSUE TITLE
Extremely bright hay in riften warehouse

### ISSUE THREAD

**Issue by LordGiggles** [Guitarninja2/septimus#408]
![enb2022_4_8_13_45_02](https://user-images.githubusercontent.com/103061810/162358995-bb43568b-98fe-4ba7-b90d-bbf1ab454e3a.jpg)

On 3.0.3.1, anniversary profile, only non-standard mod active at time of screenshot is legacy safehouse+. Using provided ENB.

**Comment by Guitarninja2** [comment]
Seems to be a problem with high poly project. I have a fix for 3.0.4
