### ISSUE TITLE
Ascendant Necromancer Hood's enchantment does not work 

### ISSUE THREAD

**Issue by ThaCheetoGuy** [Guitarninja2/septimus#412]
The item is supposed to increase your magicka by 100 points and decrease your health regeneration by 30%, but does neither of these things. It also does not appear in the active effects menu like its not enchanted at all or something.

**Comment by Xgatt** [comment]
The magicka benefit is only applied between 7pm and 5am, and that's what shows up in active effects. Funnily, the 30% debuff to health regen is always applied, but doesn't show up in your active effects. The magicka boost Magic Effect has the description for both effects.

Not really a Septimus bug, and more of a quirk with how the hood itself is set up in the original mod.
