### ISSUE TITLE
Floating lavender in whiterun hold [AE Profile]

### ISSUE THREAD

**Issue by Elektrosh0ck** [Guitarninja2/septimus#413]
Not anything serious, just floating lavender plant
![floating lav 1](https://user-images.githubusercontent.com/75975273/162546882-cb6c184a-bc13-49c7-a463-3226d8ad2311.png)
![floating lav 2](https://user-images.githubusercontent.com/75975273/162546889-9efbc113-0f69-4b76-88ff-26a7945fffbc.png)

**Comment by Guitarninja2** [comment]
Fixed in 3.0.4
