### ISSUE TITLE
Mending Potions Don't Work In Survival Mode

### ISSUE THREAD

**Issue by believeinyuna** [Guitarninja2/septimus#423]
Survival Mode disables all health regen. Orcs have a passive with Aetherius that allow them to regen health, and it works with Survival Mode on. But Mending Potions (at least the ones I've found in the world, haven't attempted to make any with alchemy) do not regen health, when drunk they do absolutely nothing.

**Comment by Durgenage** [comment]
Mending potions work fine for me. Survival mode does NOT disable health regen, it reduces it by 100%. Taking a Potion of Mending gives you +20% health regeneration. It might seem like it does 'absolutely nothing' but it's just very slow.
