### ISSUE TITLE
Fish Anywhere Updates 

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#424]
https://www.nexusmods.com/skyrimspecialedition/mods/60915
We downloaded it when it was .2.  it is now .5.
Some significant fixes

![Screenshot_20220411-001301_Chrome](https://user-images.githubusercontent.com/2394842/162732983-1eaeafc7-956a-4a3a-a8ae-a75b2117ad90.jpg)

**Comment by Guitarninja2** [comment]
Updated
