### ISSUE TITLE
Mod Suggestion: ElSopa textures

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#426]
Consider adding ElSopa textures:

quivers
https://www.nexusmods.com/skyrimspecialedition/mods/65921

keys (may already be in)
https://www.nexusmods.com/skyrimspecialedition/mods/48209

papers
https://www.nexusmods.com/skyrimspecialedition/mods/33422  (including ones we get from courier)

2 unique pickaxes
https://www.nexusmods.com/skyrimspecialedition/mods/29400

Her Ash Piles  (With No Skull version)
https://www.nexusmods.com/skyrimspecialedition/mods/22106 Remade

Clavicus Mask
https://www.nexusmods.com/skyrimspecialedition/mods/30819

Big Backpack
https://www.nexusmods.com/skyrimspecialedition/mods/36445

**Comment by Guitarninja2** [comment]
Added the ones I wanted
