### ISSUE TITLE
Mods to Consider: Hide and Sneak, Fishing, and Cooking Granting Skill XP.

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#429]
Hide and Sneak Grants Sneak XP
https://www.nexusmods.com/skyrimspecialedition/mods/66149

Skillful Fisherman - Fishing gives [One Handed/Alchemy] skill
https://www.nexusmods.com/skyrimspecialedition/mods/58780

Skillful Chef - Cooking gives Alchemy XP
https://www.nexusmods.com/skyrimspecialedition/mods/2214

Atronach Forge Grants Conjuration Skill
https://www.nexusmods.com/skyrimspecialedition/mods/19301

Spider Crafting Grants Enchanting Skill
https://www.nexusmods.com/skyrimspecialedition/mods/19302

**Comment by Guitarninja2** [comment]
Added Hide and Seek and Skillful chef. Thanks!
