### ISSUE TITLE
Patch Suggestion: Add "Carriage and Ferry Travel Overhaul" destination for Blackthorn

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#43]
I built the Blackthorn boat dock hoping that it would be like a hearthfire jetty and integrate into CFTO, but it doesn't seem that way. I can take the boat out of Blackthorn, but it would be great to take a carriage ride there.

**Comment by Guitarninja2** [comment]
I can look into this yeah.

**Comment by rsrogers4** [comment]
Thanks Guitar Ninja. I just realized that Heartwood Mill has a carriage destination and is very close to Blackthorn, so this should be extremely low priority compared to other requests.

**Comment by rsrogers4** [comment]
Can already teleport to Blackthorn, and fast travel using boats away from it.
