### ISSUE TITLE
Jayserpa Mods:  Sensible Bribes/Mercenary Costs.  Leaps of Faith.  Wound Overlays

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#430]
Let me look at the mods they made to see if there are any winners we don't have
https://www.nexusmods.com/skyrimspecialedition/mods/55450  Sensible Bribes based off of Speechcraft and not level
https://www.nexusmods.com/skyrimspecialedition/mods/53074  Leaps of Faith.  I heard much good about this
https://www.nexusmods.com/skyrimspecialedition/mods/45677  Dynamic Mercenary Costs. Based off their level, and not a flat amount.
https://www.nexusmods.com/skyrimspecialedition/mods/38547  Wound Overlays.

**Comment by Guitarninja2** [comment]
I'll grab the bribes one. The rest I don't think are good fits.
