### ISSUE TITLE
Mod Reminder:  Decorating Madness

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#432]
Might need minor patching with Pilgrim, but it makes the wing and the mind look like something out of the Shivering Isles
https://www.nexusmods.com/skyrimspecialedition/mods/30503

This one is newer
https://www.nexusmods.com/skyrimspecialedition/mods/61213

**Comment by Guitarninja2** [comment]
Trying the decorating madness one for 3.1.0
