### ISSUE TITLE
Creation Club The Cause - BS Bruma Scamps Synergy   Patch Issue

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#433]
https://www.nexusmods.com/skyrimspecialedition/mods/59591
We use the ESL version of this...
Which was archived recently due to this message

> Archived the ESL version as it appears something went wrong with it when converting from ESP to ESL.

however, some guy made a corrected ESL
https://drive.google.com/file/d/16GpECHVAZev8UKjPUnlD_AAyYvuASYPG/view

**Comment by Guitarninja2** [comment]
Done
