### ISSUE TITLE
Mod to Update: Favorite Misc Items Update Fixes Double Spell Tome message

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#434]
https://www.nexusmods.com/skyrimspecialedition/mods/42750

> Version 3.6.0
> Fixed bug where book processing code could run outside the favorites menu (ie. this fixes double notifications when learning spells and other related issues)

Fixed bug with garbled strings in book description

**Comment by Guitarninja2** [comment]
Done
