### ISSUE TITLE
LODT Display

### ISSUE THREAD

**Issue by Kodi450** [Guitarninja2/septimus#436]
LODT display is not counting some items and is very buggy with transferring items. One time I put items to be moved (80 items or so) and 0 was displayed yet I see them displayed and the log doesn't update. Another time I displayed 72 items and only 1 was logged.

**Comment by Xgatt** [comment]
Where are you getting the display count from? I find that that curator's guide book is quite behind on the count, but the LOTD checklist / settings MCM gets it right. Also, when you you the display prep station, does it seem to give an accurate number?

**Comment by Kodi450** [comment]
I try to use the display prep station but found that it doesn't work for some of the items for some reason so I moved to use the other station. I have been checking the book and as far as I can tell in other Sep playthroughs (before 3.0.0+) it would show the right number. I am reporting this issue because I know LOTD has quest which unlocks at points when you hit different amounts of displayed items.
