### ISSUE TITLE
Reminder: Update BUVARP SE RE to Make Troll Lower Level at Low Levels.  Also Get Rid of Ice in Troll Pit

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#437]
https://www.nexusmods.com/skyrimspecialedition/mods/64703
This is the mod by [AndrealphusVIII](https://www.nexusmods.com/skyrimspecialedition/users/5646623) which removes the ice meshes in the Troll Pit.

https://www.nexusmods.com/skyrimspecialedition/mods/56120
This is the mod which fixes the troll issue (ticket #404 ) in Bleakfalls Barrow.

Version 1.1
- Added Bash Tags, which hopefully fixes any Wrye Bash's Bashed Patch issues.
- Thomas Encounter in Bleak Falls Barrow: Added a low level variation called Wounded Troll, which should be easier to kill for low level characters.
- Stalleo:
- I gave him a clan name: "Deep-Heart"
- I renamed his bodyguards: "Fridya Thrice-Dawn" and "Lokrenor Sable-Song"
- I made Stalleo and the bodyguards into unique NPCs, no more leveled templates. This requires them to have facegen.
- Renamed the bandit chief in Treva's Watch to "Brurid the Contemptible", to reflect the dialogue from Stalleo mentioning him.
- Renamed the corpses inside Treva's Watch to Golius Daro, Vaella Deep-Heart and Ilske Deep-Heart
- If you do his quest to reclaim Treva's Watch, Infiltration, and see the corpses, you can tell Stalleo you found them and get a small reward.
- After the quest, Stalleo and his bodyguards will sandbox at the fort, instead of returning to the camp.
- After another 24 hours, a gravestone will be made inside the courtyard of the fort for Stalleo's deceased wife and daughter.
- Illia will now sandbox in the Bee and Barb in Riften after her quest, Repentance.
- NPCs that don't actually exist in Vanilla, but are otherwise mentioned:
- Athel Newberry:
- Was only mentioned in the letter, called No Word Yet, in Vanilla.
- I added him to the Moorside Inn in Morthal, as placeholder for an upcoming quest for Rune.
- Tuldinwae:
- Was only mentioned in the letter, called Timely Offer.
- I added her as a hunter to the hunter's camp south of Kynesgrove.
- Savela Nethri:
- Daughter of Selveni Nethri: Saveli was only mentioned by Selveni in dialogue.
- I added her to the Retching Netch Cornerclub in Raven Rock.
- Dead NPCs that have coffins added for:
- Lilija Snow-Shod: The daughter of Vulwulf Snow-Shod in Riften, was a healer "battlemaiden" for the Stormcloaks. Fell in battle fighting Imperials. -> Added her coffin in the Hall of the Dead in Riften.
- Friga Shatter-Shield: The daughter of Shatter-Shield in Windhelm. Got killed by the Butcher prior to the player visiting the city. -> Added her coffin in the Hall of the Dead in Windhelm.
- Naalia Aretino: Mother of Aventus Aretino. Died prior to the player first visiting Windhelm. Added her coffin in the Hall of the Dead in Windhelm.
- Lavinia: Daughter of Mathies and Indara Caerellia. Added her gravestone at the Falkreath graveyard.
- Dead NPCs added to Sovngarde:
- Lilija Snow-Shod
- Friga Shatter-Shield
- Lavinia
- Reyda: sister of Narfi
- Kilthinius Dandoril: Manufacturer of the traps at Riftweald Manor, only mentioned in a letter To the Owner﻿. -> added him as an NPC to the Winking Skeever in Solitude.

**Comment by Guitarninja2** [comment]
Done
