### ISSUE TITLE
Potential bug: Strobing water mesh

### ISSUE THREAD

**Issue by rsrogers4** [Guitarninja2/septimus#44]
First, let me say how much I love this wabbajack. I am seeing some strobing water mesh with 1.8.5 that I hadn't seen earlier when looking out to the lake from the Riften docks. I also saw strobing water at the lake near Nilhelm towers. I'm using a GeForce GTX 1080 FTW with the latest drivers, Cathedralist ENB, Septimus 1.8.5, and FOV 90 (in case that matters). It is so gorgeous I really don't care, and am happily continuing to play, but I thought I should let you know just in case it is something you wish to investigate/fix.

**Comment by Guitarninja2** [comment]
Yeah some sort of screenshot is ideal but I will take a look.

**Comment by rsrogers4** [comment]
Here is a little video of it. I remembered that I didn't select bordered/windowless in the base game when I first set this up (but kept it at full screen) so this might be an issue that's on me and not the build.

https://user-images.githubusercontent.com/508163/144478657-7cb4e679-f4dc-4e85-b9e4-49db77bdd761.MOV

**Comment by Guitarninja2** [comment]
Thanks yeah. One option is to enable enb water btw. That will make it look better in general. Unless it's already on. In which case try turning it off.

**Comment by rsrogers4** [comment]
Thanks. I didn't notice this before, because I hadn't looked up high enough. The source of the strobing seems to be high up in the mountains (occlusion issue?) and I believe that might be accurately reflected in the water. Again, no big deal, but you seem to be polishing this modlist to perfection so I thought I'd do my part by reporting potential issues.

**Comment by rsrogers4** [comment]
I'm not seeing this in a fresh 1.9.0 game. Great job with this - so polished and solid.

**Comment by Guitarninja2** [comment]
Eyyyy. Awesome. I'll close this out.
