### ISSUE TITLE
Crashes in Dumzbthar when running any ENB in 3.04

### ISSUE THREAD

**Issue by johnennion** [Guitarninja2/septimus#441]
Hi,
I am experiencing crashes when I am in Dumzbthar for Lucien's quest. Turning off the ENB with SHIFT-F10 for the entirety of my time in the dungeon keeps the crashes from happening. There's a short reddit thread where I found the troubleshooting solution of turning off ENB: https://old.reddit.com/r/skyrimmods/comments/pdpey2/dumzbthar_keeps_crashing/

I already did the pagefile trick from the instructions and my compy has a 3070 and 32GB of RAM so I don't think it's related to the performance stats on my computer.

**Comment by Guitarninja2** [comment]
Fixed in 3.0.5
