### ISSUE TITLE
Mod Recommendation: Angi's Tweaks

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#443]
https://www.nexusmods.com/skyrimspecialedition/mods/44914
I think we could really use this.  Changes the Angi training from granting skill levels to granting skill xp.  Allows you to replenish your practice arrows.  Fixes Angi's dialogue when you shoot arrows.

> Reworks XP gain from Angi's archery challenges to be independent of your current skill level, and allows you to gain extra XP from practicing on your own. Your character won't be a beginner anymore if you can complete all the challenges!
> 
> Description
> 
> Major changes to Angi's Camp / Archery Practice (dunArcherQST):
> 
> - Completing Angi's challenges now gives flat XP bonuses that scale with the challenge difficulty (2400 XP in total).
> - You can continue to ask Angi for Practice Arrows when you're running low after completing her challenges.
> - You can continue to gain a small amount of XP from practicing at the target range. (Make sure to use the Practice Arrows!)
> - Practice Arrows will automatically re-spawn by the target range if you are about to run out.
> 
> Minor changes:
> 
> - Angi will no longer react to you (e.g. "Be careful!") when firing your bow.
> - Angi will hit the far target accurately when demonstrating (may only affect new games). You may still notice arrows teleporting upwards after they collide; this is an unavoidable issue with how the engine handles AI aiming.
> - Angi will correctly start with the middle target and not skip the right target during the final demonstration.
> - Angi will consider you a friend after completing the first challenge. You will become an enemy if you threaten her, so don't pick that option if you're planning to use the Ebony Blade.

**Comment by Guitarninja2** [comment]
Added for 3.0.5
