### ISSUE TITLE
Vosis Dragon Priest Mask

### ISSUE THREAD

**Issue by tigerboy985** [Guitarninja2/septimus#445]
The entrance to the tomb where the mask is, in the Tomb of the Unknown Soldier is blocked off.

**Comment by tigerboy985** [comment]
![image](https://user-images.githubusercontent.com/43861729/163863993-6216b0a4-cfa5-4997-a602-479d44d5ef38.png)

**Comment by Guitarninja2** [comment]
Fixed in 3.0.5
