### ISSUE TITLE
Invisible 1st person arms (female) with Temple Ordinator armor from Sforzinda Imitations mod

### ISSUE THREAD

**Issue by icydawgfish** [Guitarninja2/septimus#449]
![enb2022_4_20_18_24_34](https://user-images.githubusercontent.com/104177910/164577168-c56099ef-f607-48a6-a7ed-231c95b24d4f.jpeg)

See attached photo

**Comment by icydawgfish** [comment]
light armor version, both variants. haven't tested heavy or unarmored versions

**Comment by Guitarninja2** [comment]
Unfortunately other than disabling the armor outright I don't think I can fix this.
