### ISSUE TITLE
Game flashes when performing sprinting attack

### ISSUE THREAD

**Issue by SeptimusFan2112** [Guitarninja2/septimus#456]
This occurs when you have a weapon drawn and jump while sprinting, as well as occurring for many weapons when performing a sprinting attack. The entire screen flashes for a split second in what almost looks like an FoV change. It's pretty disorienting and fairly awful to look at, can be a bit disruptive to gameplay too if you're the kind of person to use a lot of sprinting attacks. I've found that this is caused by SmoothCam. Disabling SmoothCam gets rid of this issue. However, naturally, one likely would want to keep SmoothCam. As such, I and some others found that a recent, previous version of SmoothCam (1.5) does not have this issue while installed in the list.

**Comment by Guitarninja2** [comment]
This should be fixed in 3.1.0
