### ISSUE TITLE
Mod Reminder: Pickpocket Anyone  and Pickpocket Reset

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#459]
Moved from #418 

Pickpocket Anyone

https://www.nexusmods.com/skyrimspecialedition/mods/38702
Doesn't conflict with anything.
Could be a good optional
Makes Security a valid combat build ...provided you are able to pickpocket

Pickpocket Reset
https://www.nexusmods.com/skyrimspecialedition/mods/13838?tab=description
Causes NPCs who are pickpocketed to have their inventory reset after 2 game days

**Comment by Guitarninja2** [comment]
I didn't want to go for the reset one but I did grab pickpocket anyone.
