### ISSUE TITLE
1.8.6 INI files are ... not following TPF performance settings?

### ISSUE THREAD

**Issue by Zriel88** [Guitarninja2/septimus#46]
So, I wanted to check what settings where being applied on this new version and I can see it doesn't follow the recommended ones from the performance section of TPF. Don't know if intended or it was overlooked.

![image](https://user-images.githubusercontent.com/8926895/144557867-82c89af0-21d7-442f-b284-1d1c9326492b.png)
![image](https://user-images.githubusercontent.com/8926895/144557914-f6cb1d55-3b65-4acf-89e6-3f3ca75f548b.png)
![image](https://user-images.githubusercontent.com/8926895/144557937-71d40c63-2cb6-4a54-9fb6-c213652ecf77.png)

I have added the files that are supposed to go in a performance profile.
[Septimus - Anniversary Edition INI Performance.zip](https://github.com/Guitarninja2/septimus/files/7647357/Septimus.-.Anniversary.Edition.INI.Performance.zip)

**Comment by Guitarninja2** [comment]
Yeah that's correct. The only important changes IMO for TPF settings were the grass changes which significantly improves distant grass. I covered this in No Grass In Objects though so Bethini is ok to change whatever. If you want to make changes to the ini files with bethini that's okay. I have actually lowered the default settings somewhat so lower spec users have a better chance to run the list but you can increase these values back up to high if you want.
