### ISSUE TITLE
Mod Suggestion:  Shalidor's Migrant Portals

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#460]
https://www.nexusmods.com/skyrimspecialedition/mods/17262

Portals locked behind Shalidor's Maze.  When you return to Shalidor's Maze after completing it, an entrance to a new and harder dungeon appears.   These portal stones are the reward for completing it.   

Basically a Magic alternative to the Smithing Dwemer Teleporters

**Comment by Guitarninja2** [comment]
I prefer the dwemer ones tbh.
