### ISSUE TITLE
Upon starting a new game I cannot move.

### ISSUE THREAD

**Issue by Drewbies** [Guitarninja2/septimus#461]
I play primarily with a controller; after character creation I'd made my character- spent a good hour on him to make him cool and stuff.
Though after character creation I couldn't move. At all. Not with my controller or my keyboard. Though when I used the power attack with my fists I was sent forward so I did that to get to the lexicon thing. And then again to get up the stairs; then I encountered an infinite load screen. I had just installed Septimus 3 and was really excited.

**Comment by Guitarninja2** [comment]
Please come by the discord. It's going to be very difficult to diagnose here.
