### ISSUE TITLE
Dragon Priest Combat Start Up Issues

### ISSUE THREAD

**Issue by SharpeGuy** [Guitarninja2/septimus#465]
I only faced two which was last update (3.0.4) but there seems to be something going on with the combat. The two that I faced took a good 30 seconds to a minute to get going if I didn't do anything. They kinda just floated around me menacingly with spells in there hands until all of sudden they switched to a staff and started attacking. If I were to constantly attack them right as they get out of the coffin or whatever, they just become stun-locked it seems but I'm not necessarily bashing/power attacking the whole time.

Pointed this out in discord and PringleNinja said it was a known issue, likely caused by Konahrik's Accoutrements. I mentioned that I had the same issue when I tried the latest release of the Elysium Remastered modlist which I believe does not have that mod. He said interesting and linked this bug report link.

**Comment by Guitarninja2** [comment]
This is unfortunately a vanilla issue.
