### ISSUE TITLE
Mod Suggestion: Honorhall Orphanage Bugfixes and Expansion

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#471]
https://www.nexusmods.com/skyrimspecialedition/mods/66955

Fixes some long-standing bugs about Honorhall that Hearthfire introduced.  Namely involving newly orphaned children never going to the orphanage for various reasons.

Also adds 3 more beds.

**Comment by Guitarninja2** [comment]
Added in 3.1.0
