### ISSUE TITLE
Mod Update: Remiel

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#473]
https://www.nexusmods.com/skyrimspecialedition/mods/51874

Since we installed her... she became marriageable

> Version 1.3.31
> > Added missing textures

> Version 1.3.4
> > Bug Fixes: Included missing scripts in the BSA so that romance will proceed; tweaked when certain dialogues are available; tweaked the probability of idle lines going off; compressed voice files

> Version 1.3.3
> > Bug Fixes: Remi's Horse will now spawn when you ask her to ride; can ask Remi to heal you even if you refused the first go around; Remi can make more of her dwarven bolts using dwarven scrap metal; removed unused properties from the crossbow quest scripts; added a way for Remi to lockpick doors; set Scrap to not be attacked during Starting Quest; decreased how often Remi talks; made a new "race" so that he will no longer detonate upon death; fixed a script attached to an incorrect alias; marked unique dwemer items as quest items
> > Banter: J'zargo
> > Features: Romance and Marriage

> Marriage: Complete the "Upgrades" quest and/or hear Remi talk about her history with her father and with her previous relationship. This will allow the player to start "flirting" with her, with a dialogue option aptly named 'flirt.' Each option in this category will award a set number of points toward setting her as a marriage candidate, with 12 points being the minimum for marrying her. You'll know you've reached this because Remi will have force-greeted you four times to 'flirt' back. At this point, the marriage proceeds according to vanilla. After marriage, Remi will have some unique idles, will make you meals, will run a "store," and can be given gifts. She'll also banter with your kids.

**Comment by Guitarninja2** [comment]
Done for 3.1.0
