### ISSUE TITLE
Mod Suggestions:  Catir Club - Immersive Creation Club Integration

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#474]
https://www.nexusmods.com/skyrimspecialedition/mods/66864

I posted this in Dev, along with CRP.

Fixes many of the problems with these two CC.
Like the Stalking Cultists.

I see no issue with Halls of Rielle.

> Catir Club
> This modpage serves as a hub for small-scale modules intended to organically integrate certain pieces of Creation Club content into the game. These files focus on eliminating threadbare quests and distributing content across the vanilla game, as well as occasionally fixing bugs or issues with creation files.
> 
> Currently, I offer modules for the following, each requiring the corresponding Creation:
> 
> The Contest
> All quest content, books, notes, and NPCs related to The Contest creation have been removed.
> The Fists of Randagulf have been given to Skjor and can be looted from him after he gets krevved. Their tempering recipe has also been fixed; it was broken in the original The Contest file. The mod edits Skjor's outfit in order to give him the Fists of Randagulf. In the base game, he is the only NPC that uses this outfit, so this is not an issue, but on the off chance that you are using a mod that gives another NPC Skjor's outfit or modifies that outfit somehow, it will need to be patched. The alternative to modifying the outfit would be directly editing Skjor's NPC record, which would be significantly worse for compatibility.
> The Iceblade of the Monarch can now be found by a skeleton in Harstrad Cave, guarded by a powerful spriggan. Beware, though, as taking the Blade may provoke the sacred spring's other guardians.
> Nimhe (the spider boss in Nchuand-Zel) is now a fearsome Web Mother, and has appropriate art, stats, and abilities.
> The actual weapon and armor, respectively, have not been edited at all and will be fully compatible with rebalancing mods.
> 
> Goldbrand
> Goldbrand can now be found in a master locked display case in the Emperor's office on the Katariah. This is in line with the story of The Elder Scrolls: Legends. If you don't care to pick the lock, the Emperor's Display Case Key can be found on his dresser.
> Quest content from the Goldbrand creation no longer occurs ingame.
> Sivdur's Respite is now a standalone dungeon and has proper location tags, making it clearable. The dungeon has been overhauled with a new puzzle, improved lighting and ambience, tweaked progression, and an overhauled final fight.
> Boethiah Cultists in Sivdur's Respite have been replaced by Tomb Raiders. A note about the puzzle can be found on one's body.
> The actual weapon has not been edited at all and will be fully compatible with rebalancing mods.
> 
> More Creations will likely follow when I get around to them. Integrations that require advanced quest design will be processed separately.
> These files are primarily intended for use in modlists, but can be downloaded independently as well to jazz up your CC/AE content on your own.
>

**Comment by Guitarninja2** [comment]
Move this to the dev board
