### ISSUE TITLE
Legacy of Dragonborn (Quest: Shattered Legacy) in Dragon's Fall 2 CDTs within 10 min

### ISSUE THREAD

**Issue by Xeohul** [Guitarninja2/septimus#481]
Hallo,

I experienced 2 CDTs within 10 min, but only in the dungeon Dragon's Fall. I have an unmodified version of Spetimus 3.0.5 .
I got no issue in other places so far.
[Crash_2022_5_4_22-26-31.txt](https://github.com/Guitarninja2/septimus/files/8630777/Crash_2022_5_4_22-26-31.txt)
[Crash_2022_5_4_22-42-31.txt](https://github.com/Guitarninja2/septimus/files/8630778/Crash_2022_5_4_22-42-31.txt)

**Comment by Guitarninja2** [comment]
Can't reproduce it myself sadly.
