### ISSUE TITLE
Can't install modlist

### ISSUE THREAD

**Issue by caseyelaw** [Guitarninja2/septimus#485]
![Screenshot 2022-05-07 114000](https://user-images.githubusercontent.com/105122774/167264169-7651b1f5-6f4b-495d-9358-438ddb09a4b6.jpg)

**Comment by SnellieSnale** [comment]
Have the same issue :)
![image](https://user-images.githubusercontent.com/77302181/167270269-e49dfadf-985f-4192-b430-240ef30a92e6.png)

**Comment by Guitarninja2** [comment]
This should be fixed now.
