### ISSUE TITLE
LotD texture issue during 'Shattered Legacy' quest

### ISSUE THREAD

**Issue by Sani7y** [Guitarninja2/septimus#486]
Mummified Corpse NPCs (Regular and Blademaster) in the Sancre Tor Catacombs location used during the 'Shattered Legacy' quest are missing textures and are.... Green.
![image](https://user-images.githubusercontent.com/105140051/167281123-ccfd83cc-da30-4dbe-a3a2-aab20c6e3514.png)
![image](https://user-images.githubusercontent.com/105140051/167281177-28b16854-b7d2-4eed-a3d5-682923006699.png)

****

**Comment by Sani7y** [comment]
Possible conflict with DRAUGR and LotD?

**Comment by Guitarninja2** [comment]
Fixed in 3.1
