### ISSUE TITLE
Animations for bound katana are broken

### ISSUE THREAD

**Issue by SnellieSnale** [Guitarninja2/septimus#488]
When in first person, the animations with the bound katana seem broken when not equiped with a shield. If you have a shield equiped, they seem fine.
![Screenshot_1](https://user-images.githubusercontent.com/77302181/168110638-68a043a2-ba2f-457d-b81f-08c8055a5bed.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/77302181/168110654-92548ffb-d3dd-4923-98de-8d2fa3a6fca0.jpg)

When in third person, the animations with the bound katana seem broken when equiped with a shield. If you don't have a shield equiped, they seem fine.
![Screenshot_3](https://user-images.githubusercontent.com/77302181/168110844-946d1069-daeb-4a05-83e6-9049b7b093cd.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/77302181/168110853-e6a02b52-a2ca-4706-b663-8c0b69b859a6.jpg)

I'm not sure if this is the same for the other katana's in game, or if it's just an issue with the bound version. I seem to remember that their was an issue in the past with them, but that it got fixed.

Edit: I'm using the latest version v3.0.5.4

**Comment by Guitarninja2** [comment]
That is how katana animations are with animated armory
