### ISSUE TITLE
Blackthorn landscape issue

### ISSUE THREAD

**Issue by Calcyon85** [Guitarninja2/septimus#49]
There is a spot in the landscape that you can see through in the Blackthorn area. The spot is behind one of the buildings to the North of the Trader building.

![Blackthorn Landscape issue](https://user-images.githubusercontent.com/94953858/144736644-6284ec28-205f-41fe-80ac-51d5b2c9528e.jpg)

**Comment by Calcyon85** [comment]
Not sure if this mod will fix it completely but it has an ESP Replacer for Blackthorn that cleans up some dirty edits and whatnot.

https://www.nexusmods.com/skyrimspecialedition/mods/57365?tab=description

**Comment by Guitarninja2** [comment]
So that might actually fix it. It was actually conflicting with another mod already but the patch you linked will probably fix some other issues so I'll include it and give it a go.

**Comment by Guitarninja2** [comment]
This should be sorted out in the new beta now
