### ISSUE TITLE
Bug: Minor Visual Bugs in Windhelm

### ISSUE THREAD

**Issue by dk232** [Guitarninja2/septimus#51]
Misplaced lantern in the graveyard, supposed to be hanging on a branch but floating because of the tree replacer:
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 06 - 19 27 07 94](https://user-images.githubusercontent.com/95635765/144945370-bc7730c4-46c7-4a9f-b015-72cc82a48f81.png)

Objects disappear/pop in around the roof area of the Gray Quarter when looking at certain angles: 
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 06 - 19 28 40 44](https://user-images.githubusercontent.com/95635765/144945912-5909cc9e-5e9c-4ee2-9604-944f02ea2f25.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 06 - 19 28 47 71](https://user-images.githubusercontent.com/95635765/144945986-d8916da4-a875-429c-b47d-aeab61a3dc68.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 06 - 19 29 15 64](https://user-images.githubusercontent.com/95635765/144946025-7429a8b0-8cdc-4250-a7e2-451adcf56dcb.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 06 - 19 29 25 16](https://user-images.githubusercontent.com/95635765/144946338-580fccd4-f072-4364-800e-bf7ac95a6181.png)

**Comment by Guitarninja2** [comment]
This should be fixed in 2.0.0-beta5
