### ISSUE TITLE
Mod Suggestion: Less Visually Obstructive Cloak Spells + Zombie Voice Remover

### ISSUE THREAD

**Issue by Aphiberg** [Guitarninja2/septimus#52]
https://www.nexusmods.com/skyrimspecialedition/mods/16964

https://www.nexusmods.com/skyrimspecialedition/mods/6783

I strongly believe these are both important COL tweaks. The cloaks as they are currently implemented are far too obstructive and block almost half my field of view. For the Zombie voices, the addition of the Staff of Worms to have a permanent undead follower early on really highlights how incredibly annoying the zombie moaning is. For that one I recommend the optional "idle remover only" file.

**Comment by Guitarninja2** [comment]
Gonna put the cloaks thing in. Other one not atm.
