### ISSUE TITLE
Survival visual bug on argonian

### ISSUE THREAD

**Issue by ItsJustFreddy87** [Guitarninja2/septimus#54]
Weird particle effect happened on argonian when using survival mode. Other races are no effected.
![SkyrimSE 2021-12-09 22-39-31](https://user-images.githubusercontent.com/95867363/145417205-d7c317fb-dbd6-4fc2-af7c-f1d7e1d0a10e.png)
![SkyrimSE 2021-12-09 22-39-38](https://user-images.githubusercontent.com/95867363/145417248-f46ebf84-1ab1-4164-ba45-54b4e4e85cab.png)
![SkyrimSE 2021-12-09 22-40-14](https://user-images.githubusercontent.com/95867363/145417278-00a081f3-1ca6-48e2-be63-fd8080afc376.png)

**Comment by Guitarninja2** [comment]
Finally fixed. Will be in the next update :D
