### ISSUE TITLE
Naked T Posing Bandit

### ISSUE THREAD

**Issue by Calcyon85** [Guitarninja2/septimus#55]
I came across this guy in Valtheim Towers.

![SkyrimSE_EKceIL2D5s](https://user-images.githubusercontent.com/94953858/145538017-4141be08-ab33-42a2-bc08-010ba25c4674.jpg)

**Comment by dk232** [comment]
OBIS isn't included in this list, is it?

**Comment by Guitarninja2** [comment]
This one is likely a weird one-off issue. I went and checked the location and it was ok.
