### ISSUE TITLE
Floating Rocks in Worldspace

### ISSUE THREAD

**Issue by Recoveres** [Guitarninja2/septimus#56]
There are floating rocks near the Entrance to "Velothi Mountain Tunnels, also there are spots where you can see through the world space .
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 10 - 09 37 30 72](https://user-images.githubusercontent.com/95914997/145565205-d694ff55-08c5-4940-8feb-e2bf4f9ff3a3.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 10 - 09 37 37 85](https://user-images.githubusercontent.com/95914997/145565226-39f66a16-9f6e-494e-8b74-fa9896dd5f51.png)
 
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 10 - 09 37 45 97](https://user-images.githubusercontent.com/95914997/145565241-c4e8809b-0161-4010-a319-a707c77c0ace.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 10 - 09 37 51 57](https://user-images.githubusercontent.com/95914997/145565258-bd936058-19ad-4883-9a08-ed9297ca4213.png)
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 10 - 09 38 03 47](https://user-images.githubusercontent.com/95914997/145565279-dcc5ea8e-6268-456d-86f2-cb055b2f904a.png)

**Comment by Guitarninja2** [comment]
Fixed in 1.9.1
