### ISSUE TITLE
Specific Rock / Gravel Texture visible through water and fog

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#57]
![grafik](https://user-images.githubusercontent.com/95932072/145612469-9a01276b-e39e-444f-a714-658eb12e5ca0.png)
![grafik](https://user-images.githubusercontent.com/95932072/145612491-e5fddcd3-ef32-439e-b749-0fc93bb0c453.png)
![grafik](https://user-images.githubusercontent.com/95932072/145612512-7163f8e0-72eb-4b29-a5ba-bd7735e089d1.png)

**Comment by Guitarninja2** [comment]
Fixed bb
