### ISSUE TITLE
Water seam @ Solitude Docks

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#58]
![grafik](https://user-images.githubusercontent.com/95932072/145614279-f4973ac8-0633-4d21-9bcd-716daebffb9e.png)
![grafik](https://user-images.githubusercontent.com/95932072/145614301-d06754cb-60b0-4da5-beeb-708a32d634ff.png)

**Comment by Guitarninja2** [comment]
Finally found the issue deep in the water records lol. Should be fixed in the next update.
