### ISSUE TITLE
Dragons Too Strong?

### ISSUE THREAD

**Issue by Guitarninja2** [Guitarninja2/septimus#59]
Comment thread about fixing dragons

**Comment by Jynxed943** [comment]
WAY TOO MUCH HEALTH !

**Comment by LesskarrWolfe** [comment]
i like a good tough battle but the dragons  deffenetly have too much health so would deff appreciate some sort of nerf to that or atleast option somewhere to be able to tweak/customize it

**Comment by NaveenS96** [comment]
Too much health!

**Comment by Guitarninja2** [comment]
I'm gonna start by just halving the health of all the dragon's and see if that's enough.

**Comment by Guitarninja2** [comment]
Health tweaks are here for those who want it:
https://www.nexusmods.com/Core/Libs/Common/Widgets/DownloadPopUp?id=248250&game_id=1704

**Comment by Guitarninja2** [comment]
Gonna close this for now as I've made some tweaks. If it's a further issue we can re-open
