### ISSUE TITLE
Mod Suggestion: Khajiits Steal Too - Caravan Fence Option

### ISSUE THREAD

**Issue by PappyToast** [Guitarninja2/septimus#62]
I really like this mod and I think it adds a lot for any character that is a thief but doesn't want to join the thieve's guild for any reason. https://www.nexusmods.com/skyrimspecialedition/mods/18231

**Comment by Guitarninja2** [comment]
Checking this one now. Seems neat.

**Comment by Guitarninja2** [comment]
This is in the next update :D
