### ISSUE TITLE
Skyrim Immersive Creatures additions overwritten by other mods.

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#64]
I noticed the recently added `OBIS SE.esp` overwrote some book leveled lists.
Namely removing the book `_00BookGoblinsofSkyrim "The Goblins: A Study"` which was added by `Skyrim Immersive Creatures Special Edition.esp` from various leveled lists.

Looking at some other leveled lists... it looks like `Skyrim Immersive Creatures Special Edition.esp` lost a good deal of its Leveled Actor additions to other mods overwriting them.  Mods like `GrahlsOnSolsteim.esp`,  `BriDraugurOverhaul.esp` 

...probably other things were lost, but these are the ones I stumbled across when going through it in SSSEdit.

**Comment by Webmetz** [comment]
Going to go back through with a fine tooth comb and make a report.

**Comment by Guitarninja2** [comment]
Thank you again yeah. With open world loot overwriting a lot of leveled lists on top it can get a bit hectic lol. I'll try to get these in a better state for 1.9.2

**Comment by Guitarninja2** [comment]
Okay yeah I went through as well and it was just several records that needed to be forwarded in the CRP and merged. I'll check against your list once you take a look. Thanks!

**Comment by Webmetz** [comment]
These are the SIC items which are removed from lists.

### Spell Tome and Book Lists
LitemSpellTomes50Destruction 
-  _00LItemSpellTomesDestruction50 
  - This list contains spells added by SIC

**LitemSpellTomes50AllDestruction** 
-  _00LItemSpellTomesDestruction50 
  - This list contains spells added by SIC

**LItemSpellTomes75Conjuration**
- _00LItemSpellTomesConjuration75Skeleton
  - This list contains spells added by SIC to summon SIC variants of skeletons.
- _00LItemSpellTomesConjuration75Daedra
  - This list contains spells added by SIC to summon SIC variants of daedra

**LItemSpellTomes75AllConjuration**
- _00LItemSpellTomesConjuration75Skeleton
  - This list contains spells added by SIC to summon SIC variants of skeletons.
- _00LItemSpellTomesConjuration75Daedra 
  - This list contains spells added by SIC to summon SIC variants of daedra

**LItemSpellTomes50Spells**
-  _00LItemSpellTomesDestruction50 
  - This list contains spells added by SIC

**LItemSpellTomes75Spells**
- _00LItemSpellTomesConjuration75Skeleton
  - This list contains spells added by SIC to summon SIC variants of skeletons.
- _00LItemSpellTomesConjuration75Daedra 
  - This list contains spells added by SIC to summon SIC variants of daedra

**LItemBookClutter**
- _00BookGoblinsofSkyrim "The Goblins: A Study" [BOOK:6E6E357B]

### Leveled NPC List

**LCharAnimalSnowFields**  
- SIC added the following lists and Grahl Removed them.  These lists contain the new animals added by SIC.  I recommend adding them back in to the final list.
- _00LCharCreatureSnowPrey 
- _00LCharCreatureSnow_LOW
- _00LCharCreatureSnow_MID 
- _00LCharCreatureSnow_HIGH
- _00LCharCreatureSnow_HIGHER 

**LCharDraugr05BossWithDragonPriest**
- There are 10 SIC variants that were removed.  I recommend adding the Skeleton and Shade variants from SIC to the final list.
  - _00EncSkeletonPriest01_lvl50 "Skeleton Priest"
  - _00EncSkeletonPriest02_lvl50 "Skeleton Priest"
  - _00EncSkeletonPriestShade01_lvl50 "Skeleton Priest Shade"
  - _00EncSkeletonPriestShade02_lvl50 "Skeleton Priest Shade"
  - _00EncSkeletonPriest03_lvl50 "Skeleton Priest"
  - _00EncDraugrPriest01_lvl50 "Draugr Priest"
  - _00EncDraugrPriest02_lvl50 "Draugr Priest"
  - _00DLC2EncSkeletonAcolyte01_lvl50 "Skeleton Acolyte"
  - _00DLC2EncSkeletonAcolyte02_lvl50 "Skeleton Acolyte"
  - _00DLC2EncSkeletonAcolyte03_lvl50 "Skeleton Acolyte"

**LCharDraugrBossNoDragonPriest**
- BriDraugurOverhaul adds only 1 variant to this list and keeps the vanilla ones. The variant added is  `BriDOEncDraugrStalhrimTemplateBoss "Draugr Winter King"`.   
- SIC, however, replaces the 4 Melee draugr bosses with 3 lists and 5 new draugr.
- **Recommendation**: SIC should take priority, and add the Winter King to the final list.

**LCharDraugrWarlock**   AND  **LCharDraugrWarlockFemale**  AND **LCharDraugrWarlockMale** 
- BriDraugurOverhaul only adds a level 30 Draugur Warlock List
- SIC adds a level 40, 50, 60, and 70 list.  
- **Recommendation:**  Add the level 40/50/60/70 lists to the final list

**DLC2LCharAnimalForestPredator**:  
- SIC replaces the vanilla skeever/wolf with new variants.   GrahlsOnSolsteim returns the vanilla lists, adds the Grahls, and removes the trolls.   My recommendation to forward the changes from SIC onwards and remove the vanilla ones that SIC removed
 - _00LCharSkeever
 - _00EncWolf

**DLC2LCharAnimalMountainSnowPredator**:  
- SIC replaces the vanilla ice wolves with new variants.   GrahlsOnSolsteim returns the vanilla wolves, adds the Grahls, and removes the trolls.   My recommendation to forward the changes from SIC onwards and remove the vanilla ones that SIC removed
 - _00EncWolfIce

**Comment by Guitarninja2** [comment]
This is in the next update/1.10 beta. Thank  you!
