### ISSUE TITLE
Mod Suggestion: Wield Clutter

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#68]
https://www.nexusmods.com/skyrimspecialedition/mods/26025

Adds wieldable miscellaneous items in the world, and ways to craft them.  Bandits can be found using them..

(Made by the Creator of Relics of Hyrule.)

**Comment by Webmetz** [comment]
I did the grunt work of making WC compatible with the list.  
[Septimus - Conflict Resolution Plus WC - CC Edition.zip](https://github.com/Guitarninja2/septimus/files/7700706/Septimus.-.Conflict.Resolution.Plus.WC.-.CC.Edition.zip)

[Septimus - Conflict Resolution Plus WC.zip](https://github.com/Guitarninja2/septimus/files/7700718/Septimus.-.Conflict.Resolution.Plus.WC.zip)

The CC edition one includes the CC Fishing Rods 

Long story short for the edits.

### Normal Edition
- Added **WC_WieldClutter1H100** to **LItemBanditWeapon1H**
- Added **WC_WieldClutter2H100 [LVLI:2300FC81]** to **LItemBanditWeapon2H**
- Added to **LItemBookClutter**
  - **WC_BookHandyManSecretWeapon "Handyman's Secret Weapon"**
  - **WC_BookTrorgarsBroom "Trorgar's Broom"**}
- Added to **OBIS_LItem_CustomShieldsLight**
  - WC_ArmorCartWheel "Cart Wheel" [ARMO:23003EBD]
  - WC_ArmorFirewoodShield "Firewood" [ARMO:23003EC0]
- Added to **OWL_Weapon_Draugr_1H**
  - WC_EmbalmingPick "Embalming Pick" [WEAP:23003396]

### CC Edition
- All of the above
- Fixes the Wield Clutter Crafting recipes to not make Wield Clutter Fishing Poles, instead making the CC Imperial Fishing Rod. Therefore eliminates the possibility of making WC Fishing Rods from misc Fishing Poles, if they ever appear.
- Substitutes the Wield Clutter Fishing Pole Weapons with CC Fishing Rods in **WC_WieldClutter1H100**

**Comment by Guitarninja2** [comment]
Probably too many weapons on top of having heavy and animated armory tbh.
