### ISSUE TITLE
Mod Suggestion: Skyrim SafeSave System Overhaul

### ISSUE THREAD

**Issue by Zriel88** [Guitarninja2/septimus#73]
This has been posted on discord and wanted to know a bit more what you think about it. I'm not so knowleadgable about the save system on Skyrim and if this really does something and would be nice to have or is just a placebo.
https://www.nexusmods.com/skyrimspecialedition/mods/19399

**Comment by Guitarninja2** [comment]
This one is good but I don't want to include by default. People can install it if they like it though.
