### ISSUE TITLE
Mod Suggestion: Hearthfire Extended

### ISSUE THREAD

**Issue by Webmetz** [Guitarninja2/septimus#83]
Mod Suggestion:
Hearthfire Extended
https://www.nexusmods.com/skyrimspecialedition/mods/8450

What it does
1) More Plantables
2) Allows you to craft and placehearthfire furniture in other places. Also allows you to buy rugs from Caravan Merchants and place them.
3) Better Hearthfire house cellars
4) Distributed Hearthfire Content like Churns
5) Much more

**Comment by Guitarninja2** [comment]
Could you check this one in game and make sure there are no issues? If so I'm down to include it.

**Comment by Guitarninja2** [comment]
I'm worries this will interact poorly with cc content or something since it now changes hearthfire
