### ISSUE TITLE
Add Antiquary with SEPARATE PATCH NO CRP

### ISSUE THREAD

**Issue by Guitarninja2** [Guitarninja2/septimus#84]
https://www.nexusmods.com/skyrimspecialedition/mods/44413

**Comment by Webmetz** [comment]
I'll work on ASAP.  I'll document what changes I make, and ones which might need looking at.

**Comment by Webmetz** [comment]
[Septimus-Antiquary-CRP.zip](https://github.com/Guitarninja2/septimus/files/7701239/Septimus-Antiquary-CRP.zip)

I don't have time to document changes right now, or even test it.

This definitely needs testing with the archmage robes in the archmage quarters.  As they are force equipped on a mannequin.  It also undoes the 'separated' robe by WAACF.    I was unsure if they would work right with the updated editor id.

I will test tomorrow

**Comment by Webmetz** [comment]
Prep:
Install in this order
https://www.nexusmods.com/skyrimspecialedition/mods/44413
1. Antiquary Enhanced Eiditon
2. Antiquary Apothecary Patch
3. Antiquary Classical Lichdom Patch

Install the CRP Patch
[Septimus-Antiquary-CRP v2.zip](https://github.com/Guitarninja2/septimus/files/7708560/Septimus-Antiquary-CRP.v2.zip)


------------------------------------

### `DA05SaviorsHide "Savior's Hide" [ARMO:0002AC61]`
Material changed to Hide and Scaled. 
Classified as Cold Clothing

### `dunGauldurAmulet "The Gauldur Amulet" [ARMO:0002D773]`
Classified as WAF Jewelry. 

### `DA13Spellbreaker "Spellbreaker" [ARMO:00045F96]`
Armor rating dropped to 36 to match WAACF

### `DA02Armor "Ebony Mail" [ARMO:00052794]`
Gained WAACF keyword `WAF_VisuallyDarkArmor [KYWD:01AF0126]`

### `ArmorDragonPriestMaskMoonstoneHelmet "Morokei" [ARMO:00061C8B]`
Becomes 'Protective Clothing' item. 
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskEbonyHelmet "Nahkriin" [ARMO:00061CA5]`
Ebony Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskCorondrumHelmet "Volsung" [ARMO:00061CAB]`
Scaled Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskBronzeHelmet "Krosis" [ARMO:00061CB9]`
Classified as Elven Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskOrichalumHelmet "Rahgot" [ARMO:00061CC0]`
Changed to Orcish Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskIronHelmet "Hevnoraak" [ARMO:00061CC1]`
Changed to Iron Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskMarbleHelmet "Otar" [ARMO:00061CC2]`
Changed to Glass Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskSteelHelmet "Vokun" [ARMO:00061CC9]`
Changed to Steel / Steel Plate Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ArmorDragonPriestMaskUltraHelmet "Konahrik" [ARMO:00061CD6]`
Changed to Dragonscale / Dragonplate Material
Hair no longer clips
Classified a Daedric artifact to avoid being sold to Vendors.

### `ANTQ_ArchmageBoots "Archmage's Boots" [ARMO:0007C92E]`
No changes for Antiquary. Ignored armor from WAACF as the enchantment provides armor.

### `ANTQ_ArchmageRobes "Archmage's Robes" [ARMO:0007C932]`
No Changes Antiquary.
**NEEDS TESTING AS IT IS AUTO-EQUIPPED ON A MANNEQUIN IN OCW**

### `MS11NecromancerAmulet "Necromancer's Amulet" [ARMO:000C891D]`
No Changes Antiquary

### `ClavicusVileMask "Masque of Clavicus Vile" [ARMO:000D2846]`
Registered as Daedric Artifact.

### `dunLabyrinthianMazeCircletReward "Diadem of the Savant" [ARMO:000F9904]`
Registered as Jewelry for WAACF

### `ANTQ_ArchmageRobesHooded "Archmage's Robes" [ARMO:0010F570]`
Forwarded WAACF script that swaps it into a 2 piece garment.
Hooded Robe transformed into Body item.
**NEEDS TESTING AS IT IS AUTO-EQUIPPED ON A MANNEQUIN IN OCW**

### `DLC1nVampireBloodMagicRingBeast "Ring of the Beast" [ARMO:0200E7FD]`
Classified as Jewlery Item

### `DLC1nVampireBloodMagicRingErudite "Ring of the Erudite" [ARMO:0200E7FE]`
Classified as Jewlery Item

### `DLC2ArmorAcolyteMaskShock "Zahkriisos" [ARMO:04024037]`
Now takes up Hair slot to avoid hair clipping
Ebony Material
Classified as Daedric Artifact in regards to vendors

### `DLC2ArmorAcolyteMaskFire "Ahzidal" [ARMO:040240FE]`
Now takes up Hair slot to avoid hair clipping
Draugr Material
Classified as Daedric Artifact in regards to vendors

### `DLC2ArmorAcolyteMaskFrost "Dukaan" [ARMO:040240FF]`
Now takes up Hair slot to avoid hair clipping
Now Light Armor
Stalhrim Material

### `DLC2MiraakMaskNew "Miraak" [ARMO:04029A62]`
Now takes up Hair slot to avoid hair clipping
Classified as Daedric Artifact in regards to vendors
Classified as Cultist in regards to WAACF

### `DLC2ClothesMiraakGloves "Miraak's Gloves" [ARMO:0402B0F9]`
Classified as Cultist in regards to WAACF
8 Armor
Gains WAACF Perk Fists (which I assume increases unarmed damage0

### `DLC2ClothesMiraakRobes "Miraak's Robes" [ARMO:0402B0F7]`
### `DLC2MKClothesMiraakRobes "Miraak's Robes" [ARMO:04039151] `
### `DLC2MKMiraakRobes1 "Miraak's Robes" [ARMO:04039D1E]`
### `DLC2MKMiraakRobes2 "Miraak's Robes" [ARMO:04039D20]`
### `DLC2MKMiraakRobes3 "Miraak's Robes" [ARMO:04039D22]`
### `DLC2MKMiraakFightRobes1 "Miraak's Robes" [ARMO:0403C0F7]`
### `DLC2MKMiraakFightRobes2 "Miraak's Robes" [ARMO:0403C0F9]`
### `DLC2MKMiraakFightRobes3 "Miraak's Robes" [ARMO:0403C0FA]`
### `DLC2MKMiraakFightRobes4 "Miraak's Robes" [ARMO:0403C0FB]`
### `DLC2MKMiraakFightRobes5 "Miraak's Robes" [ARMO:0403C0FC]`
### `DLC2MKMiraakFightRobes6 "Miraak's Robes" [ARMO:0403C0FD]`
Classified as Cultist in regards to WAACF
Gains 25 Armor

### `DLC2MKMiraakMask1L "Miraak" [ARMO:04039D2B]`
### `DLC2MKMiraakMask2L "Miraak" [ARMO:04039D2E]`
### `DLC2MKMiraakMask3L "Miraak" [ARMO:04039D2F]`
Now takes up Hair slot to avoid hair clipping
Vendors treat as Daedric Artifact
Dragonscale Material

### `DLC2MKMiraakMask1H "Miraak" [ARMO:04039FA1]`
### `DLC2MKMiraakMask2H "Miraak" [ARMO:04039FA2]`
### `DLC2MKMiraakMask3H "Miraak" [ARMO:04039FA3]`
Now takes up Hair slot to avoid hair clipping
Vendors treat as Daedric Artifact
Dragonplate Material

### `DLC2MKMiraakFightMask1 "Miraak's Mask" [ARMO:0403C0F1]`
### `DLC2MKMiraakFightMask2 "Miraak's Mask" [ARMO:0403C0F2]`
### `DLC2MKMiraakFightMask3 "Miraak's Mask" [ARMO:0403C0F3]`
### `DLC2MKMiraakFightMask4 "Miraak's Mask" [ARMO:0403C0F4]`
### `DLC2MKMiraakFightMask5 "Miraak's Mask" [ARMO:0403C0F5]`
### `DLC2MKMiraakFightMask6 "Miraak's Mask" [ARMO:0403C0F6]`
Now takes up Hair slot to avoid hair clipping
Vendors treat as Daedric Artifact
Cultist Material

### `DLC2ClothesMiraakBoots "Miraak's Boots" [ARMO:0403D2AF]`
Cultist Material

### `ANTQ_SummonDragonPriest "Conjure Dragon Priest" [MGEF:0010FC12]`
### `DLC2HazardExpSpiderPoisonDamageFFContact "Poison Hazard" [MGEF:0401445B]`
### `DLC2crPoisonConcAimed "Poison" [MGEF:0401CAB7]`
### `DLC2ExpSpidercrPoisonConcAimed "Poison" [MGEF:040200CE]`
### `DLC2ExpSpiderPoisonBombFFContact "Poison" [MGEF:040322AF]`
### `DLC2ExpSpiderPoisonEnemyEFFdmgShow "Poison" [MGEF:04036DA8]`
Gains ISC changes

### `DA03RuefulAxe "The Rueful Axe" [WEAP:0001C4E6]`
Becomes Silver and gains silver scripts
However is tempered by Ebony (odd huh?)
Gains ISC changes
Vendors treat as Daedric Artifacts, and won't buy it

### `DA10MaceofMolagBal "Mace of Molag Bal" [WEAP:000233E3]`
Daedric Material

### `DA09Dawnbreaker "Dawnbreaker" [WEAP:0004E4EE]`
No changes from Antiquary aside from increased value

### `DA06Volendrung "Volendrung" [WEAP:0002ACD2]`
Gains WAACF increased stagger
Becomes a Loud weapon

### `dunAnsilvundGhostblade "Ghostblade" [WEAP:00094A2B]`
Becomes Silent weapon

### `dunSaarthalStaffJyrikStaff "Staff of Jyrik Gauldurson" [WEAP:000E5F43]`
Gains new appearance from BriDraugr Overhaul

### `DLC2MKMiraakSword1 "Firstblade" [WEAP:040397F6]`
### `DLC2MKMiraakSword2 "Firstblade" [WEAP:04039FB1]`
### `DLC2MKMiraakSword3 "Firstblade" [WEAP:04039FB4]`
Increased Weight.
Gains Foul Spike keyword

### `WinterholdCollegeArchMageQuarters "Arch-Mage's Quarters" [CELL:000CAB92]`
Forwarded Luminosity Changes
Antiquary disables the mannequin with the robes.  I re-enabled them

**Comment by Guitarninja2** [comment]
Alrighty this is in now. Thanks!
