### ISSUE TITLE
Skin and face problems on orc 

### ISSUE THREAD

**Issue by Recoveres** [Guitarninja2/septimus#88]
Made an orc character but after loading in his face texture got "bleached" into "human skin tone " i guess besides that his whole body texture is just glissening
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 12 13 - 06 32 06 04](https://user-images.githubusercontent.com/95914997/145758248-ceb0c006-6f1b-4b6e-bb72-1a2bf641073a.png)
.

**Comment by Recoveres** [comment]
on 1.9.1  if that helps

**Comment by Guitarninja2** [comment]
This is on a fresh install right? Wow I definitely have not seen that lol.

**Comment by Guitarninja2** [comment]
I'll take some time to test this one myself.

**Comment by Recoveres** [comment]
its updated from 1.9 to 1.9.1 but i had the same thing (with the face) happening on 1.9 with highelf . Someone on the discord showed me that if you go into "showracemenu" it fixes the face, so dunno what the problem is.
But it shows after the first loading screen (when you tp into helgen after choosing hadvar or the stormcloack guy) with the face bug and if you go into showracemenu then it fixes it without you needing to change anything on your face.

**Comment by Recoveres** [comment]
I will say i did not see it happen with cats and lizards so i guess the elfes and orcs share something with the human races that makes them get the "human skin color" after loading in

**Comment by Recoveres** [comment]
I looked it over with some base presets (the normal game ones) you dont get the buggy face so it seems like if you change something in the character creation it comes to the face bug, dunno what specificly tho. I will say that i was a bit confused by the Eyebrows of the orcs since it looks a bit weird in creation but that is my only guess as to what could be it , but im not too well versed in this stuff, so im sorry if this doesnt help

**Comment by Guitarninja2** [comment]
Ok actually fixed in the next update
