### ISSUE TITLE
Mod suggestion: The Ascension (lite)

### ISSUE THREAD

**Issue by Codegeekman** [Guitarninja2/septimus#90]
Given that prelude to purgatory was removed, I think The Ascension lite should be considered now that prelude isn't in the list (as the two are atm incompatible), as of the writing of this post it is also updated fairly frequently.
https://www.nexusmods.com/skyrimspecialedition/mods/58983

**Comment by Guitarninja2** [comment]
I don't want to deal with the additional compatibility issues here right now.
