### ISSUE TITLE
Broken model

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#95]
![grafik](https://user-images.githubusercontent.com/95932072/145998567-2eca294c-0156-4db1-8c66-9f863e7bbdee.png)
![grafik](https://user-images.githubusercontent.com/95932072/145998604-f1c28f62-e958-4dbb-b475-3c35f234ff62.png)

**Comment by Guitarninja2** [comment]
Have not seen this yet. Mega weird.
