### ISSUE TITLE
Load order issue prevents warpaints from actually showing up

### ISSUE THREAD

**Issue by 69jns420** [Guitarninja2/septimus#96]
![grafik](https://user-images.githubusercontent.com/95932072/145999332-d50271fb-4ca7-4bc3-9e99-ef45b4d300e9.png)
Before "fix":

![grafik](https://user-images.githubusercontent.com/95932072/145999383-677dd5ed-72c8-41a7-9357-ffd04d36617d.png)

After moving Tempered Skins above the warpaint mods: (Painterlys paints now actually show up in the racemenu :D )

![grafik](https://user-images.githubusercontent.com/95932072/145999444-31aa4705-9c85-488b-b693-f8b84f41e06b.png)

**Comment by Guitarninja2** [comment]
Fixed in the next update
