### ISSUE TITLE
The Male Orc head skin color does not match the body color.

### ISSUE THREAD

**Issue by broodwarjc** [Guitarninja2/septimus#97]
![image](https://user-images.githubusercontent.com/95047944/146035206-3f355137-49d5-48e9-a983-ae53a1a47f7e.png)

**Comment by Guitarninja2** [comment]
Gonna look at this today.

**Comment by broodwarjc** [comment]
The colors match in the Race Menu, but when I come out of it (into the room in Helgen Keep), the heads are all pale colored compared to the Green bodies.

**Comment by Guitarninja2** [comment]
I think this is an actual issue. I'll make sure it's fixed in the next version. Workaround is to open race menu again after making your character and closing it.

**Comment by Guitarninja2** [comment]
Okay I think this might be fixed for real this time with 1.10. Stay tuned.
