### ISSUE TITLE
Trouble Installing Septimus

### ISSUE THREAD

**Issue by TurtleHD** [Guitarninja2/septimus#98]
Im at the point where wabbajack is attempting to copy base files from my game folder but is unable to hash the download, im playing with a fresh install, log is below

0.01 - Maximum amount of old logs reached (50 >= 50)
0.02 - Found 0 old log files to delete
0.02 - Deleted 0 log files, failed to delete 0 logs
0.21 - Wabbajack Build - f0820514e7dfce84303dde8ef09257bdbbf59c25
0.21 - Running in D:\Wabbajack\2.5.3.3
0.22 - Detected Windows Version: 10.0.19042.0
0.22 - System settings - (15.9GB RAM) (6.8GB Page), Display: 1920 x 1080 (7.9GB VRAM - VideoMemorySizeMb=10240)
0.22 - Pagefile below recommended! Consider increasing to 20000MB. A suboptimal pagefile can cause crashes and poor in-game performance.
0.24 - Steam: Found no Regex matches in Steam Config at c:/program files (x86)/steam\config\config.vdf
0.24 - Getting new Wabbajack version list
0.24 - Steam: Found game Fireworks Mania (1079260) at "D:\Steam\steamapps\common\Fireworks Mania"
0.25 - Steam: Found game Persona 4 Golden (1113000) at "D:\Steam\steamapps\common\Persona 4 Golden"
0.25 - Steam: Found game PlanetSide 2 (218230) at "D:\Steam\steamapps\common\PlanetSide 2"
0.25 - Steam: Found game The Elder Scrolls IV: Oblivion  (22330) at "D:\Steam\steamapps\common\Oblivion"
0.25 - Steam: Found game Fallout: New Vegas (22380) at "D:\Steam\steamapps\common\Fallout New Vegas"
0.25 - Steam: Found game Steamworks Common Redistributables (228980) at "D:\Steam\steamapps\common\Steamworks Shared"
0.25 - Steam: Found game The Legend of Heroes: Trails in the Sky (251150) at "D:\Steam\steamapps\common\Trails in the Sky FC"
0.25 - Steam: Found game iRacing (266410) at "D:\Steam\steamapps\common\iRacing"
0.25 - Steam: Found game BeamNG.drive (284160) at "D:\Steam\steamapps\common\BeamNG.drive"
0.25 - Steam: Found game The Witcher 3: Wild Hunt (292030) at "D:\Steam\steamapps\common\The Witcher 3"
0.25 - Steam: Found game Stardew Valley (413150) at "D:\Steam\steamapps\common\Stardew Valley"
0.25 - Steam: Found game The Elder Scrolls V: Skyrim Special Edition (489830) at "D:\Steam\steamapps\common\Skyrim Special Edition"
0.25 - Steam: Found game Monster Hunter: World (582010) at "D:\Steam\steamapps\common\Monster Hunter World"
0.25 - Steam: Found game Okami HD (587620) at "D:\Steam\steamapps\common\Okami"
0.25 - Steam: Found game Journey (638230) at "D:\Steam\steamapps\common\Journey"
0.25 - Steam: Found game CODE VEIN (678960) at "D:\Steam\steamapps\common\CODE VEIN"
0.25 - Steam: Found game Flower (966330) at "D:\Steam\steamapps\common\Flower"
0.25 - GOG: GOG was not found in the registry
0.25 - BethNet: Unable to open Registry Keys SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net and SOFTWARE\WOW6432Node\Bethesda Softworks\Bethesda.net
0.25 - EGS: Unable to open Registry Key SOFTWARE\Epic Games\EOS
0.25 - Origin: LocalContent directory at C:\ProgramData\Origin\LocalContent does not exist
0.55 - Wabbajack Version: 2.5.3.3
0.82 - Build server is down
1.02 - Build server is down
23.74 - Loading ModLists from GitHub
32.01 - Starting to install Septimus
32.01 - Cleaning VFS, this may take a bit of time
32.04 - Starting Installer Task
32.04 - Installation has Started
32.04 - Configuring Processor
32.05 - Install Folder: D:\Septimus
32.05 - Downloads Folder: D:\Septimus\downloads
32.05 - Game Folder: D:\Steam\steamapps\common\Skyrim Special Edition
32.05 - Wabbajack Folder: D:\Wabbajack\2.5.3.3
32.05 - Drive watcher is starting. Will warn at 8GB and error at 4GB
32.06 - Starting Drive watcher on D:\ currently 1.3TB free out of 1.8TB
32.06 - Validating Game ESMs
32.07 - Creating Output Folders
32.13 - Optimizing ModList
32.14 - Optimizing ModList directives
34.3 - Looking for files to delete
34.33 - Cleaning empty folders
35.17 - Looking for unmodified files
36.62 - Updating ModList
36.62 - Optimized 193998 directives to 193998 required
36.66 - Hashing Archives
36.67 - Looking for files to hash
36.71 - Found 1219 total files, 1174 matching filesize
132.95 - Downloading Missing Archives
132.95 - Missing 23 archives
132.95 - Getting Nexus API Key, if a browser appears, please accept
132.97 - Loading server whitelist
133.1 - Loaded permissions for 622 servers and 272 Google Drive files
133.17 - Downloading Data_Skyrim - Textures0.bsa
133.17 - Downloading Data_Skyrim.esm
133.17 - Downloading Data_Skyrim - Sounds.bsa
133.17 - Downloading Data_Skyrim - Textures3.bsa
133.17 - Downloading Nemesis.Unlimited.Behavior.Engine.v0.84-beta.rar
133.17 - Downloading Data_Skyrim - Shaders.bsa
133.17 - Downloading Data_Skyrim - Misc.bsa
133.18 - Downloading Data_Skyrim - Interface.bsa
133.53 - Loading for alternative to uq8KT2b+f9A=
133.63 - No alternative for uq8KT2b+f9A= could be found
133.63 - Downloading Septimus - DynDOLOD Output CC-58229-1-9-0-1638762384.zip
133.79 - Hashed download is incorrect
133.79 - Loading for alternative to 3JVsfCnKO8s=
133.84 - No alternative for 3JVsfCnKO8s= could be found
133.84 - Downloading Septimus - DynDOLOD Output-58229-1-9-0-1638762078.zip
135.33 - Hashed download is incorrect
135.33 - Loading for alternative to habII97Ul5c=
135.53 - No alternative for habII97Ul5c= could be found
135.53 - Downloading Data_Update.esm
136.31 - Hashed download is incorrect
136.31 - Loading for alternative to oZzXdq/4XGs=
136.57 - No alternative for oZzXdq/4XGs= could be found
136.57 - Downloading Data_HearthFires.esm
136.61 - Hashed download is incorrect
136.61 - Loading for alternative to NSjSglH0F/s=
137.66 - No alternative for NSjSglH0F/s= could be found
137.66 - Downloading Data_Dragonborn.esm
138.7 - Hashed download is incorrect
138.7 - Loading for alternative to 32rOVH8c/vM=
141.74 - No alternative for 32rOVH8c/vM= could be found
141.74 - Downloading Data_Dawnguard.esm
141.93 - Hashed download is incorrect
141.93 - Loading for alternative to 39TE1/Ot45E=
144.54 - No alternative for 39TE1/Ot45E= could be found
144.55 - Downloading Data_ccQDRSSE001-SurvivalMode.esl
144.55 - Hashed download is incorrect
144.55 - Loading for alternative to rXB5sSgI2jM=
146.14 - No alternative for rXB5sSgI2jM= could be found
146.14 - Downloading Data_ccQDRSSE001-SurvivalMode.bsa
169.86 - Hashed download is incorrect
169.86 - Loading for alternative to n1a268FnWz0=
169.96 - No alternative for n1a268FnWz0= could be found
169.96 - Downloading Data_ccBGSSSE037-Curios.esl
170.01 - Hashed download is incorrect
170.01 - Loading for alternative to 4DgMsi8I2m8=
170.08 - No alternative for 4DgMsi8I2m8= could be found
170.08 - Downloading Data_ccBGSSSE037-Curios.bsa
187.7 - Hashed download is incorrect
187.7 - Loading for alternative to sBKaTMsnYZE=
187.88 - No alternative for sBKaTMsnYZE= could be found
187.88 - Downloading Data_ccBGSSSE025-AdvDSGS.esm
188.07 - Hashed download is incorrect
188.07 - Loading for alternative to a0m2w3eRuAw=
188.16 - No alternative for a0m2w3eRuAw= could be found
188.16 - Downloading Data_ccBGSSSE025-AdvDSGS.bsa
336.75 - Hashed download is incorrect
336.75 - Loading for alternative to cPxxYXNq0iE=
336.85 - No alternative for cPxxYXNq0iE= could be found
336.85 - Downloading Data_ccBGSSSE001-Fish.esm
337.87 - Hashed download is incorrect
337.87 - Loading for alternative to vbGhR356+Bs=
337.93 - No alternative for vbGhR356+Bs= could be found
337.93 - Downloading Data_ccBGSSSE001-Fish.bsa

**Comment by Guitarninja2** [comment]
Hey there. Come by the discord and we can get you sorted out:
https://discord.gg/tpf
