### ISSUE TITLE
Elven Hunter Helmet texture missing

### ISSUE THREAD

**Issue by Omrga** [Guitarninja2/septimus#99]
The Elven Hunter Helmet from the quest "Once a Hunter" (which is apparently not part of the quest rewards) is not properly shown, as seen in my screenshots. Do you have a quick solution for this?

![Elven1](https://user-images.githubusercontent.com/69573223/146058589-c8cd897a-20a7-4e1d-a495-20bcffa8739c.jpg)

![elven2](https://user-images.githubusercontent.com/69573223/146058600-7e075924-77d7-4712-8533-a0c191fd3e45.jpg)

**Comment by Guitarninja2** [comment]
This should be fixed now.
